//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHeadLib.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHeadLib.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ; generated by tools
        ///; AHeadLib.Net
        ///.DATA
        ///    ${EXTERNDEF_POINTERS}
        ///
        ///.CODE
        ///
        ///${FUNCTIONS}
        ///
        ///END
        /// 的本地化字符串。
        /// </summary>
        internal static string Asm_x64 {
            get {
                return ResourceManager.GetString("Asm_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; generated by tools
        ///; AHeadLib.Net
        ///.MODEL FLAT
        ///
        ///.DATA
        ///    ${EXTERNDEF_POINTERS}
        ///
        ///.CODE
        ///
        ///${FUNCTIONS}
        ///
        ///END
        /// 的本地化字符串。
        /// </summary>
        internal static string Asm_x86 {
            get {
                return ResourceManager.GetString("Asm_x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // generated by tools
        ///// AHeadLib.Net
        ///
        ///#include &lt;windows.h&gt;
        ///
        ///#if defined(_WIN64) || defined(_X64) || defined(WIN64) || defined( __LP64__ )
        ///#define __X64_BUILD__ 1
        ///#else
        ///#define __X64_BUILD__ 0
        ///#endif
        ///
        ///// checked get function in native dll
        ///static void* __CheckedGetFunction(HMODULE module, const char* methodName)
        ///{
        ///    void* Result = GetProcAddress(module, methodName);
        ///
        ///    if (Result == NULL)
        ///    {
        ///        char szMessage[256];
        ///        wsprintfA(szMessage, &quot;Failed bind method:%s&quot;, methodNam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CppHelper {
            get {
                return ResourceManager.GetString("CppHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // generated by tools
        ///// AHeadLib.Net
        ///
        ///#include &lt;windows.h&gt;
        ///
        ///extern void __CheckedLoad();
        ///
        ///BOOL WINAPI DllMain(
        ///    HINSTANCE hinstDLL,  // handle to DLL module
        ///    DWORD fdwReason,     // reason for calling function
        ///    LPVOID lpvReserved)  // reserved
        ///{
        ///    // Perform actions based on the reason for calling.
        ///    switch (fdwReason)
        ///    {
        ///    case DLL_PROCESS_ATTACH:
        ///        // Initialize once for each new process.
        ///        // Return FALSE to fail DLL load.
        ///        __CheckedLoad();
        ///
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DllMain {
            get {
                return ResourceManager.GetString("DllMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] solution {
            get {
                object obj = ResourceManager.GetObject("solution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] vcxprojTemplate {
            get {
                object obj = ResourceManager.GetObject("vcxprojTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
