// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include <windows.h>

#if defined(_WIN64) || defined(_X64) || defined(WIN64) || defined( __LP64__ )
#define __X64_BUILD__ 1
#else
#define __X64_BUILD__ 0
#endif

// checked get function in native dll
static void* __CheckedGetFunction(HMODULE module, const char* methodName)
{
    void* Result = GetProcAddress(module, methodName);

    if (Result == NULL)
    {
        char szMessage[256];
        wsprintfA(szMessage, "Failed bind method:%s", methodName);

        OutputDebugStringA(szMessage);

#if DEBUG
        MessageBoxA(0, szMessage, "AHeadLib.Net Error", 0);
        ExitProcess(-1);
#endif
    }

    return Result;
}

void* CloseDriverPtr = NULL;
void* DefDriverProcPtr = NULL;
void* DriverCallbackPtr = NULL;
void* DrvGetModuleHandlePtr = NULL;
void* GetDriverModuleHandlePtr = NULL;
void* OpenDriverPtr = NULL;
void* PlaySoundPtr = NULL;
void* PlaySoundAPtr = NULL;
void* PlaySoundWPtr = NULL;
void* SendDriverMessagePtr = NULL;
void* WOWAppExitPtr = NULL;
void* auxGetDevCapsAPtr = NULL;
void* auxGetDevCapsWPtr = NULL;
void* auxGetNumDevsPtr = NULL;
void* auxGetVolumePtr = NULL;
void* auxOutMessagePtr = NULL;
void* auxSetVolumePtr = NULL;
void* joyConfigChangedPtr = NULL;
void* joyGetDevCapsAPtr = NULL;
void* joyGetDevCapsWPtr = NULL;
void* joyGetNumDevsPtr = NULL;
void* joyGetPosPtr = NULL;
void* joyGetPosExPtr = NULL;
void* joyGetThresholdPtr = NULL;
void* joyReleaseCapturePtr = NULL;
void* joySetCapturePtr = NULL;
void* joySetThresholdPtr = NULL;
void* mciDriverNotifyPtr = NULL;
void* mciDriverYieldPtr = NULL;
void* mciExecutePtr = NULL;
void* mciFreeCommandResourcePtr = NULL;
void* mciGetCreatorTaskPtr = NULL;
void* mciGetDeviceIDAPtr = NULL;
void* mciGetDeviceIDFromElementIDAPtr = NULL;
void* mciGetDeviceIDFromElementIDWPtr = NULL;
void* mciGetDeviceIDWPtr = NULL;
void* mciGetDriverDataPtr = NULL;
void* mciGetErrorStringAPtr = NULL;
void* mciGetErrorStringWPtr = NULL;
void* mciGetYieldProcPtr = NULL;
void* mciLoadCommandResourcePtr = NULL;
void* mciSendCommandAPtr = NULL;
void* mciSendCommandWPtr = NULL;
void* mciSendStringAPtr = NULL;
void* mciSendStringWPtr = NULL;
void* mciSetDriverDataPtr = NULL;
void* mciSetYieldProcPtr = NULL;
void* midiConnectPtr = NULL;
void* midiDisconnectPtr = NULL;
void* midiInAddBufferPtr = NULL;
void* midiInClosePtr = NULL;
void* midiInGetDevCapsAPtr = NULL;
void* midiInGetDevCapsWPtr = NULL;
void* midiInGetErrorTextAPtr = NULL;
void* midiInGetErrorTextWPtr = NULL;
void* midiInGetIDPtr = NULL;
void* midiInGetNumDevsPtr = NULL;
void* midiInMessagePtr = NULL;
void* midiInOpenPtr = NULL;
void* midiInPrepareHeaderPtr = NULL;
void* midiInResetPtr = NULL;
void* midiInStartPtr = NULL;
void* midiInStopPtr = NULL;
void* midiInUnprepareHeaderPtr = NULL;
void* midiOutCacheDrumPatchesPtr = NULL;
void* midiOutCachePatchesPtr = NULL;
void* midiOutClosePtr = NULL;
void* midiOutGetDevCapsAPtr = NULL;
void* midiOutGetDevCapsWPtr = NULL;
void* midiOutGetErrorTextAPtr = NULL;
void* midiOutGetErrorTextWPtr = NULL;
void* midiOutGetIDPtr = NULL;
void* midiOutGetNumDevsPtr = NULL;
void* midiOutGetVolumePtr = NULL;
void* midiOutLongMsgPtr = NULL;
void* midiOutMessagePtr = NULL;
void* midiOutOpenPtr = NULL;
void* midiOutPrepareHeaderPtr = NULL;
void* midiOutResetPtr = NULL;
void* midiOutSetVolumePtr = NULL;
void* midiOutShortMsgPtr = NULL;
void* midiOutUnprepareHeaderPtr = NULL;
void* midiStreamClosePtr = NULL;
void* midiStreamOpenPtr = NULL;
void* midiStreamOutPtr = NULL;
void* midiStreamPausePtr = NULL;
void* midiStreamPositionPtr = NULL;
void* midiStreamPropertyPtr = NULL;
void* midiStreamRestartPtr = NULL;
void* midiStreamStopPtr = NULL;
void* mixerClosePtr = NULL;
void* mixerGetControlDetailsAPtr = NULL;
void* mixerGetControlDetailsWPtr = NULL;
void* mixerGetDevCapsAPtr = NULL;
void* mixerGetDevCapsWPtr = NULL;
void* mixerGetIDPtr = NULL;
void* mixerGetLineControlsAPtr = NULL;
void* mixerGetLineControlsWPtr = NULL;
void* mixerGetLineInfoAPtr = NULL;
void* mixerGetLineInfoWPtr = NULL;
void* mixerGetNumDevsPtr = NULL;
void* mixerMessagePtr = NULL;
void* mixerOpenPtr = NULL;
void* mixerSetControlDetailsPtr = NULL;
void* mmDrvInstallPtr = NULL;
void* mmGetCurrentTaskPtr = NULL;
void* mmTaskBlockPtr = NULL;
void* mmTaskCreatePtr = NULL;
void* mmTaskSignalPtr = NULL;
void* mmTaskYieldPtr = NULL;
void* mmioAdvancePtr = NULL;
void* mmioAscendPtr = NULL;
void* mmioClosePtr = NULL;
void* mmioCreateChunkPtr = NULL;
void* mmioDescendPtr = NULL;
void* mmioFlushPtr = NULL;
void* mmioGetInfoPtr = NULL;
void* mmioInstallIOProcAPtr = NULL;
void* mmioInstallIOProcWPtr = NULL;
void* mmioOpenAPtr = NULL;
void* mmioOpenWPtr = NULL;
void* mmioReadPtr = NULL;
void* mmioRenameAPtr = NULL;
void* mmioRenameWPtr = NULL;
void* mmioSeekPtr = NULL;
void* mmioSendMessagePtr = NULL;
void* mmioSetBufferPtr = NULL;
void* mmioSetInfoPtr = NULL;
void* mmioStringToFOURCCAPtr = NULL;
void* mmioStringToFOURCCWPtr = NULL;
void* mmioWritePtr = NULL;
void* mmsystemGetVersionPtr = NULL;
void* sndPlaySoundAPtr = NULL;
void* sndPlaySoundWPtr = NULL;
void* timeBeginPeriodPtr = NULL;
void* timeEndPeriodPtr = NULL;
void* timeGetDevCapsPtr = NULL;
void* timeGetSystemTimePtr = NULL;
void* timeGetTimePtr = NULL;
void* timeKillEventPtr = NULL;
void* timeSetEventPtr = NULL;
void* waveInAddBufferPtr = NULL;
void* waveInClosePtr = NULL;
void* waveInGetDevCapsAPtr = NULL;
void* waveInGetDevCapsWPtr = NULL;
void* waveInGetErrorTextAPtr = NULL;
void* waveInGetErrorTextWPtr = NULL;
void* waveInGetIDPtr = NULL;
void* waveInGetNumDevsPtr = NULL;
void* waveInGetPositionPtr = NULL;
void* waveInMessagePtr = NULL;
void* waveInOpenPtr = NULL;
void* waveInPrepareHeaderPtr = NULL;
void* waveInResetPtr = NULL;
void* waveInStartPtr = NULL;
void* waveInStopPtr = NULL;
void* waveInUnprepareHeaderPtr = NULL;
void* waveOutBreakLoopPtr = NULL;
void* waveOutClosePtr = NULL;
void* waveOutGetDevCapsAPtr = NULL;
void* waveOutGetDevCapsWPtr = NULL;
void* waveOutGetErrorTextAPtr = NULL;
void* waveOutGetErrorTextWPtr = NULL;
void* waveOutGetIDPtr = NULL;
void* waveOutGetNumDevsPtr = NULL;
void* waveOutGetPitchPtr = NULL;
void* waveOutGetPlaybackRatePtr = NULL;
void* waveOutGetPositionPtr = NULL;
void* waveOutGetVolumePtr = NULL;
void* waveOutMessagePtr = NULL;
void* waveOutOpenPtr = NULL;
void* waveOutPausePtr = NULL;
void* waveOutPrepareHeaderPtr = NULL;
void* waveOutResetPtr = NULL;
void* waveOutRestartPtr = NULL;
void* waveOutSetPitchPtr = NULL;
void* waveOutSetPlaybackRatePtr = NULL;
void* waveOutSetVolumePtr = NULL;
void* waveOutUnprepareHeaderPtr = NULL;
void* waveOutWritePtr = NULL;

extern void WINAPI ASM_CloseDriver();
extern void WINAPI ASM_DefDriverProc();
extern void WINAPI ASM_DriverCallback();
extern void WINAPI ASM_DrvGetModuleHandle();
extern void WINAPI ASM_GetDriverModuleHandle();
extern void WINAPI ASM_OpenDriver();
extern void WINAPI ASM_PlaySound();
extern void WINAPI ASM_PlaySoundA();
extern void WINAPI ASM_PlaySoundW();
extern void WINAPI ASM_SendDriverMessage();
extern void WINAPI ASM_WOWAppExit();
extern void WINAPI ASM_auxGetDevCapsA();
extern void WINAPI ASM_auxGetDevCapsW();
extern void WINAPI ASM_auxGetNumDevs();
extern void WINAPI ASM_auxGetVolume();
extern void WINAPI ASM_auxOutMessage();
extern void WINAPI ASM_auxSetVolume();
extern void WINAPI ASM_joyConfigChanged();
extern void WINAPI ASM_joyGetDevCapsA();
extern void WINAPI ASM_joyGetDevCapsW();
extern void WINAPI ASM_joyGetNumDevs();
extern void WINAPI ASM_joyGetPos();
extern void WINAPI ASM_joyGetPosEx();
extern void WINAPI ASM_joyGetThreshold();
extern void WINAPI ASM_joyReleaseCapture();
extern void WINAPI ASM_joySetCapture();
extern void WINAPI ASM_joySetThreshold();
extern void WINAPI ASM_mciDriverNotify();
extern void WINAPI ASM_mciDriverYield();
extern void WINAPI ASM_mciExecute();
extern void WINAPI ASM_mciFreeCommandResource();
extern void WINAPI ASM_mciGetCreatorTask();
extern void WINAPI ASM_mciGetDeviceIDA();
extern void WINAPI ASM_mciGetDeviceIDFromElementIDA();
extern void WINAPI ASM_mciGetDeviceIDFromElementIDW();
extern void WINAPI ASM_mciGetDeviceIDW();
extern void WINAPI ASM_mciGetDriverData();
extern void WINAPI ASM_mciGetErrorStringA();
extern void WINAPI ASM_mciGetErrorStringW();
extern void WINAPI ASM_mciGetYieldProc();
extern void WINAPI ASM_mciLoadCommandResource();
extern void WINAPI ASM_mciSendCommandA();
extern void WINAPI ASM_mciSendCommandW();
extern void WINAPI ASM_mciSendStringA();
extern void WINAPI ASM_mciSendStringW();
extern void WINAPI ASM_mciSetDriverData();
extern void WINAPI ASM_mciSetYieldProc();
extern void WINAPI ASM_midiConnect();
extern void WINAPI ASM_midiDisconnect();
extern void WINAPI ASM_midiInAddBuffer();
extern void WINAPI ASM_midiInClose();
extern void WINAPI ASM_midiInGetDevCapsA();
extern void WINAPI ASM_midiInGetDevCapsW();
extern void WINAPI ASM_midiInGetErrorTextA();
extern void WINAPI ASM_midiInGetErrorTextW();
extern void WINAPI ASM_midiInGetID();
extern void WINAPI ASM_midiInGetNumDevs();
extern void WINAPI ASM_midiInMessage();
extern void WINAPI ASM_midiInOpen();
extern void WINAPI ASM_midiInPrepareHeader();
extern void WINAPI ASM_midiInReset();
extern void WINAPI ASM_midiInStart();
extern void WINAPI ASM_midiInStop();
extern void WINAPI ASM_midiInUnprepareHeader();
extern void WINAPI ASM_midiOutCacheDrumPatches();
extern void WINAPI ASM_midiOutCachePatches();
extern void WINAPI ASM_midiOutClose();
extern void WINAPI ASM_midiOutGetDevCapsA();
extern void WINAPI ASM_midiOutGetDevCapsW();
extern void WINAPI ASM_midiOutGetErrorTextA();
extern void WINAPI ASM_midiOutGetErrorTextW();
extern void WINAPI ASM_midiOutGetID();
extern void WINAPI ASM_midiOutGetNumDevs();
extern void WINAPI ASM_midiOutGetVolume();
extern void WINAPI ASM_midiOutLongMsg();
extern void WINAPI ASM_midiOutMessage();
extern void WINAPI ASM_midiOutOpen();
extern void WINAPI ASM_midiOutPrepareHeader();
extern void WINAPI ASM_midiOutReset();
extern void WINAPI ASM_midiOutSetVolume();
extern void WINAPI ASM_midiOutShortMsg();
extern void WINAPI ASM_midiOutUnprepareHeader();
extern void WINAPI ASM_midiStreamClose();
extern void WINAPI ASM_midiStreamOpen();
extern void WINAPI ASM_midiStreamOut();
extern void WINAPI ASM_midiStreamPause();
extern void WINAPI ASM_midiStreamPosition();
extern void WINAPI ASM_midiStreamProperty();
extern void WINAPI ASM_midiStreamRestart();
extern void WINAPI ASM_midiStreamStop();
extern void WINAPI ASM_mixerClose();
extern void WINAPI ASM_mixerGetControlDetailsA();
extern void WINAPI ASM_mixerGetControlDetailsW();
extern void WINAPI ASM_mixerGetDevCapsA();
extern void WINAPI ASM_mixerGetDevCapsW();
extern void WINAPI ASM_mixerGetID();
extern void WINAPI ASM_mixerGetLineControlsA();
extern void WINAPI ASM_mixerGetLineControlsW();
extern void WINAPI ASM_mixerGetLineInfoA();
extern void WINAPI ASM_mixerGetLineInfoW();
extern void WINAPI ASM_mixerGetNumDevs();
extern void WINAPI ASM_mixerMessage();
extern void WINAPI ASM_mixerOpen();
extern void WINAPI ASM_mixerSetControlDetails();
extern void WINAPI ASM_mmDrvInstall();
extern void WINAPI ASM_mmGetCurrentTask();
extern void WINAPI ASM_mmTaskBlock();
extern void WINAPI ASM_mmTaskCreate();
extern void WINAPI ASM_mmTaskSignal();
extern void WINAPI ASM_mmTaskYield();
extern void WINAPI ASM_mmioAdvance();
extern void WINAPI ASM_mmioAscend();
extern void WINAPI ASM_mmioClose();
extern void WINAPI ASM_mmioCreateChunk();
extern void WINAPI ASM_mmioDescend();
extern void WINAPI ASM_mmioFlush();
extern void WINAPI ASM_mmioGetInfo();
extern void WINAPI ASM_mmioInstallIOProcA();
extern void WINAPI ASM_mmioInstallIOProcW();
extern void WINAPI ASM_mmioOpenA();
extern void WINAPI ASM_mmioOpenW();
extern void WINAPI ASM_mmioRead();
extern void WINAPI ASM_mmioRenameA();
extern void WINAPI ASM_mmioRenameW();
extern void WINAPI ASM_mmioSeek();
extern void WINAPI ASM_mmioSendMessage();
extern void WINAPI ASM_mmioSetBuffer();
extern void WINAPI ASM_mmioSetInfo();
extern void WINAPI ASM_mmioStringToFOURCCA();
extern void WINAPI ASM_mmioStringToFOURCCW();
extern void WINAPI ASM_mmioWrite();
extern void WINAPI ASM_mmsystemGetVersion();
extern void WINAPI ASM_sndPlaySoundA();
extern void WINAPI ASM_sndPlaySoundW();
extern void WINAPI ASM_timeBeginPeriod();
extern void WINAPI ASM_timeEndPeriod();
extern void WINAPI ASM_timeGetDevCaps();
extern void WINAPI ASM_timeGetSystemTime();
extern void WINAPI ASM_timeGetTime();
extern void WINAPI ASM_timeKillEvent();
extern void WINAPI ASM_timeSetEvent();
extern void WINAPI ASM_waveInAddBuffer();
extern void WINAPI ASM_waveInClose();
extern void WINAPI ASM_waveInGetDevCapsA();
extern void WINAPI ASM_waveInGetDevCapsW();
extern void WINAPI ASM_waveInGetErrorTextA();
extern void WINAPI ASM_waveInGetErrorTextW();
extern void WINAPI ASM_waveInGetID();
extern void WINAPI ASM_waveInGetNumDevs();
extern void WINAPI ASM_waveInGetPosition();
extern void WINAPI ASM_waveInMessage();
extern void WINAPI ASM_waveInOpen();
extern void WINAPI ASM_waveInPrepareHeader();
extern void WINAPI ASM_waveInReset();
extern void WINAPI ASM_waveInStart();
extern void WINAPI ASM_waveInStop();
extern void WINAPI ASM_waveInUnprepareHeader();
extern void WINAPI ASM_waveOutBreakLoop();
extern void WINAPI ASM_waveOutClose();
extern void WINAPI ASM_waveOutGetDevCapsA();
extern void WINAPI ASM_waveOutGetDevCapsW();
extern void WINAPI ASM_waveOutGetErrorTextA();
extern void WINAPI ASM_waveOutGetErrorTextW();
extern void WINAPI ASM_waveOutGetID();
extern void WINAPI ASM_waveOutGetNumDevs();
extern void WINAPI ASM_waveOutGetPitch();
extern void WINAPI ASM_waveOutGetPlaybackRate();
extern void WINAPI ASM_waveOutGetPosition();
extern void WINAPI ASM_waveOutGetVolume();
extern void WINAPI ASM_waveOutMessage();
extern void WINAPI ASM_waveOutOpen();
extern void WINAPI ASM_waveOutPause();
extern void WINAPI ASM_waveOutPrepareHeader();
extern void WINAPI ASM_waveOutReset();
extern void WINAPI ASM_waveOutRestart();
extern void WINAPI ASM_waveOutSetPitch();
extern void WINAPI ASM_waveOutSetPlaybackRate();
extern void WINAPI ASM_waveOutSetVolume();
extern void WINAPI ASM_waveOutUnprepareHeader();
extern void WINAPI ASM_waveOutWrite();

#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:CloseDriver=ASM_CloseDriver")
#else
#pragma comment(linker, "/EXPORT:CloseDriver=_ASM_CloseDriver@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:DefDriverProc=ASM_DefDriverProc")
#else
#pragma comment(linker, "/EXPORT:DefDriverProc=_ASM_DefDriverProc@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:DriverCallback=ASM_DriverCallback")
#else
#pragma comment(linker, "/EXPORT:DriverCallback=_ASM_DriverCallback@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:DrvGetModuleHandle=ASM_DrvGetModuleHandle")
#else
#pragma comment(linker, "/EXPORT:DrvGetModuleHandle=_ASM_DrvGetModuleHandle@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetDriverModuleHandle=ASM_GetDriverModuleHandle")
#else
#pragma comment(linker, "/EXPORT:GetDriverModuleHandle=_ASM_GetDriverModuleHandle@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:OpenDriver=ASM_OpenDriver")
#else
#pragma comment(linker, "/EXPORT:OpenDriver=_ASM_OpenDriver@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:PlaySound=ASM_PlaySound")
#else
#pragma comment(linker, "/EXPORT:PlaySound=_ASM_PlaySound@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:PlaySoundA=ASM_PlaySoundA")
#else
#pragma comment(linker, "/EXPORT:PlaySoundA=_ASM_PlaySoundA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:PlaySoundW=ASM_PlaySoundW")
#else
#pragma comment(linker, "/EXPORT:PlaySoundW=_ASM_PlaySoundW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:SendDriverMessage=ASM_SendDriverMessage")
#else
#pragma comment(linker, "/EXPORT:SendDriverMessage=_ASM_SendDriverMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:WOWAppExit=ASM_WOWAppExit")
#else
#pragma comment(linker, "/EXPORT:WOWAppExit=_ASM_WOWAppExit@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxGetDevCapsA=ASM_auxGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:auxGetDevCapsA=_ASM_auxGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxGetDevCapsW=ASM_auxGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:auxGetDevCapsW=_ASM_auxGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxGetNumDevs=ASM_auxGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:auxGetNumDevs=_ASM_auxGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxGetVolume=ASM_auxGetVolume")
#else
#pragma comment(linker, "/EXPORT:auxGetVolume=_ASM_auxGetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxOutMessage=ASM_auxOutMessage")
#else
#pragma comment(linker, "/EXPORT:auxOutMessage=_ASM_auxOutMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:auxSetVolume=ASM_auxSetVolume")
#else
#pragma comment(linker, "/EXPORT:auxSetVolume=_ASM_auxSetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyConfigChanged=ASM_joyConfigChanged")
#else
#pragma comment(linker, "/EXPORT:joyConfigChanged=_ASM_joyConfigChanged@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetDevCapsA=ASM_joyGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:joyGetDevCapsA=_ASM_joyGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetDevCapsW=ASM_joyGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:joyGetDevCapsW=_ASM_joyGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetNumDevs=ASM_joyGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:joyGetNumDevs=_ASM_joyGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetPos=ASM_joyGetPos")
#else
#pragma comment(linker, "/EXPORT:joyGetPos=_ASM_joyGetPos@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetPosEx=ASM_joyGetPosEx")
#else
#pragma comment(linker, "/EXPORT:joyGetPosEx=_ASM_joyGetPosEx@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyGetThreshold=ASM_joyGetThreshold")
#else
#pragma comment(linker, "/EXPORT:joyGetThreshold=_ASM_joyGetThreshold@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joyReleaseCapture=ASM_joyReleaseCapture")
#else
#pragma comment(linker, "/EXPORT:joyReleaseCapture=_ASM_joyReleaseCapture@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joySetCapture=ASM_joySetCapture")
#else
#pragma comment(linker, "/EXPORT:joySetCapture=_ASM_joySetCapture@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:joySetThreshold=ASM_joySetThreshold")
#else
#pragma comment(linker, "/EXPORT:joySetThreshold=_ASM_joySetThreshold@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciDriverNotify=ASM_mciDriverNotify")
#else
#pragma comment(linker, "/EXPORT:mciDriverNotify=_ASM_mciDriverNotify@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciDriverYield=ASM_mciDriverYield")
#else
#pragma comment(linker, "/EXPORT:mciDriverYield=_ASM_mciDriverYield@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciExecute=ASM_mciExecute")
#else
#pragma comment(linker, "/EXPORT:mciExecute=_ASM_mciExecute@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciFreeCommandResource=ASM_mciFreeCommandResource")
#else
#pragma comment(linker, "/EXPORT:mciFreeCommandResource=_ASM_mciFreeCommandResource@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetCreatorTask=ASM_mciGetCreatorTask")
#else
#pragma comment(linker, "/EXPORT:mciGetCreatorTask=_ASM_mciGetCreatorTask@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetDeviceIDA=ASM_mciGetDeviceIDA")
#else
#pragma comment(linker, "/EXPORT:mciGetDeviceIDA=_ASM_mciGetDeviceIDA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDA=ASM_mciGetDeviceIDFromElementIDA")
#else
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDA=_ASM_mciGetDeviceIDFromElementIDA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDW=ASM_mciGetDeviceIDFromElementIDW")
#else
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDW=_ASM_mciGetDeviceIDFromElementIDW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetDeviceIDW=ASM_mciGetDeviceIDW")
#else
#pragma comment(linker, "/EXPORT:mciGetDeviceIDW=_ASM_mciGetDeviceIDW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetDriverData=ASM_mciGetDriverData")
#else
#pragma comment(linker, "/EXPORT:mciGetDriverData=_ASM_mciGetDriverData@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetErrorStringA=ASM_mciGetErrorStringA")
#else
#pragma comment(linker, "/EXPORT:mciGetErrorStringA=_ASM_mciGetErrorStringA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetErrorStringW=ASM_mciGetErrorStringW")
#else
#pragma comment(linker, "/EXPORT:mciGetErrorStringW=_ASM_mciGetErrorStringW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciGetYieldProc=ASM_mciGetYieldProc")
#else
#pragma comment(linker, "/EXPORT:mciGetYieldProc=_ASM_mciGetYieldProc@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciLoadCommandResource=ASM_mciLoadCommandResource")
#else
#pragma comment(linker, "/EXPORT:mciLoadCommandResource=_ASM_mciLoadCommandResource@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSendCommandA=ASM_mciSendCommandA")
#else
#pragma comment(linker, "/EXPORT:mciSendCommandA=_ASM_mciSendCommandA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSendCommandW=ASM_mciSendCommandW")
#else
#pragma comment(linker, "/EXPORT:mciSendCommandW=_ASM_mciSendCommandW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSendStringA=ASM_mciSendStringA")
#else
#pragma comment(linker, "/EXPORT:mciSendStringA=_ASM_mciSendStringA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSendStringW=ASM_mciSendStringW")
#else
#pragma comment(linker, "/EXPORT:mciSendStringW=_ASM_mciSendStringW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSetDriverData=ASM_mciSetDriverData")
#else
#pragma comment(linker, "/EXPORT:mciSetDriverData=_ASM_mciSetDriverData@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mciSetYieldProc=ASM_mciSetYieldProc")
#else
#pragma comment(linker, "/EXPORT:mciSetYieldProc=_ASM_mciSetYieldProc@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiConnect=ASM_midiConnect")
#else
#pragma comment(linker, "/EXPORT:midiConnect=_ASM_midiConnect@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiDisconnect=ASM_midiDisconnect")
#else
#pragma comment(linker, "/EXPORT:midiDisconnect=_ASM_midiDisconnect@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInAddBuffer=ASM_midiInAddBuffer")
#else
#pragma comment(linker, "/EXPORT:midiInAddBuffer=_ASM_midiInAddBuffer@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInClose=ASM_midiInClose")
#else
#pragma comment(linker, "/EXPORT:midiInClose=_ASM_midiInClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetDevCapsA=ASM_midiInGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:midiInGetDevCapsA=_ASM_midiInGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetDevCapsW=ASM_midiInGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:midiInGetDevCapsW=_ASM_midiInGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetErrorTextA=ASM_midiInGetErrorTextA")
#else
#pragma comment(linker, "/EXPORT:midiInGetErrorTextA=_ASM_midiInGetErrorTextA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetErrorTextW=ASM_midiInGetErrorTextW")
#else
#pragma comment(linker, "/EXPORT:midiInGetErrorTextW=_ASM_midiInGetErrorTextW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetID=ASM_midiInGetID")
#else
#pragma comment(linker, "/EXPORT:midiInGetID=_ASM_midiInGetID@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInGetNumDevs=ASM_midiInGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:midiInGetNumDevs=_ASM_midiInGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInMessage=ASM_midiInMessage")
#else
#pragma comment(linker, "/EXPORT:midiInMessage=_ASM_midiInMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInOpen=ASM_midiInOpen")
#else
#pragma comment(linker, "/EXPORT:midiInOpen=_ASM_midiInOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInPrepareHeader=ASM_midiInPrepareHeader")
#else
#pragma comment(linker, "/EXPORT:midiInPrepareHeader=_ASM_midiInPrepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInReset=ASM_midiInReset")
#else
#pragma comment(linker, "/EXPORT:midiInReset=_ASM_midiInReset@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInStart=ASM_midiInStart")
#else
#pragma comment(linker, "/EXPORT:midiInStart=_ASM_midiInStart@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInStop=ASM_midiInStop")
#else
#pragma comment(linker, "/EXPORT:midiInStop=_ASM_midiInStop@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiInUnprepareHeader=ASM_midiInUnprepareHeader")
#else
#pragma comment(linker, "/EXPORT:midiInUnprepareHeader=_ASM_midiInUnprepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutCacheDrumPatches=ASM_midiOutCacheDrumPatches")
#else
#pragma comment(linker, "/EXPORT:midiOutCacheDrumPatches=_ASM_midiOutCacheDrumPatches@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutCachePatches=ASM_midiOutCachePatches")
#else
#pragma comment(linker, "/EXPORT:midiOutCachePatches=_ASM_midiOutCachePatches@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutClose=ASM_midiOutClose")
#else
#pragma comment(linker, "/EXPORT:midiOutClose=_ASM_midiOutClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsA=ASM_midiOutGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsA=_ASM_midiOutGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsW=ASM_midiOutGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsW=_ASM_midiOutGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextA=ASM_midiOutGetErrorTextA")
#else
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextA=_ASM_midiOutGetErrorTextA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextW=ASM_midiOutGetErrorTextW")
#else
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextW=_ASM_midiOutGetErrorTextW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetID=ASM_midiOutGetID")
#else
#pragma comment(linker, "/EXPORT:midiOutGetID=_ASM_midiOutGetID@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetNumDevs=ASM_midiOutGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:midiOutGetNumDevs=_ASM_midiOutGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutGetVolume=ASM_midiOutGetVolume")
#else
#pragma comment(linker, "/EXPORT:midiOutGetVolume=_ASM_midiOutGetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutLongMsg=ASM_midiOutLongMsg")
#else
#pragma comment(linker, "/EXPORT:midiOutLongMsg=_ASM_midiOutLongMsg@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutMessage=ASM_midiOutMessage")
#else
#pragma comment(linker, "/EXPORT:midiOutMessage=_ASM_midiOutMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutOpen=ASM_midiOutOpen")
#else
#pragma comment(linker, "/EXPORT:midiOutOpen=_ASM_midiOutOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutPrepareHeader=ASM_midiOutPrepareHeader")
#else
#pragma comment(linker, "/EXPORT:midiOutPrepareHeader=_ASM_midiOutPrepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutReset=ASM_midiOutReset")
#else
#pragma comment(linker, "/EXPORT:midiOutReset=_ASM_midiOutReset@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutSetVolume=ASM_midiOutSetVolume")
#else
#pragma comment(linker, "/EXPORT:midiOutSetVolume=_ASM_midiOutSetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutShortMsg=ASM_midiOutShortMsg")
#else
#pragma comment(linker, "/EXPORT:midiOutShortMsg=_ASM_midiOutShortMsg@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiOutUnprepareHeader=ASM_midiOutUnprepareHeader")
#else
#pragma comment(linker, "/EXPORT:midiOutUnprepareHeader=_ASM_midiOutUnprepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamClose=ASM_midiStreamClose")
#else
#pragma comment(linker, "/EXPORT:midiStreamClose=_ASM_midiStreamClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamOpen=ASM_midiStreamOpen")
#else
#pragma comment(linker, "/EXPORT:midiStreamOpen=_ASM_midiStreamOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamOut=ASM_midiStreamOut")
#else
#pragma comment(linker, "/EXPORT:midiStreamOut=_ASM_midiStreamOut@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamPause=ASM_midiStreamPause")
#else
#pragma comment(linker, "/EXPORT:midiStreamPause=_ASM_midiStreamPause@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamPosition=ASM_midiStreamPosition")
#else
#pragma comment(linker, "/EXPORT:midiStreamPosition=_ASM_midiStreamPosition@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamProperty=ASM_midiStreamProperty")
#else
#pragma comment(linker, "/EXPORT:midiStreamProperty=_ASM_midiStreamProperty@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamRestart=ASM_midiStreamRestart")
#else
#pragma comment(linker, "/EXPORT:midiStreamRestart=_ASM_midiStreamRestart@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:midiStreamStop=ASM_midiStreamStop")
#else
#pragma comment(linker, "/EXPORT:midiStreamStop=_ASM_midiStreamStop@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerClose=ASM_mixerClose")
#else
#pragma comment(linker, "/EXPORT:mixerClose=_ASM_mixerClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsA=ASM_mixerGetControlDetailsA")
#else
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsA=_ASM_mixerGetControlDetailsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsW=ASM_mixerGetControlDetailsW")
#else
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsW=_ASM_mixerGetControlDetailsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetDevCapsA=ASM_mixerGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:mixerGetDevCapsA=_ASM_mixerGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetDevCapsW=ASM_mixerGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:mixerGetDevCapsW=_ASM_mixerGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetID=ASM_mixerGetID")
#else
#pragma comment(linker, "/EXPORT:mixerGetID=_ASM_mixerGetID@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetLineControlsA=ASM_mixerGetLineControlsA")
#else
#pragma comment(linker, "/EXPORT:mixerGetLineControlsA=_ASM_mixerGetLineControlsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetLineControlsW=ASM_mixerGetLineControlsW")
#else
#pragma comment(linker, "/EXPORT:mixerGetLineControlsW=_ASM_mixerGetLineControlsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetLineInfoA=ASM_mixerGetLineInfoA")
#else
#pragma comment(linker, "/EXPORT:mixerGetLineInfoA=_ASM_mixerGetLineInfoA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetLineInfoW=ASM_mixerGetLineInfoW")
#else
#pragma comment(linker, "/EXPORT:mixerGetLineInfoW=_ASM_mixerGetLineInfoW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerGetNumDevs=ASM_mixerGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:mixerGetNumDevs=_ASM_mixerGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerMessage=ASM_mixerMessage")
#else
#pragma comment(linker, "/EXPORT:mixerMessage=_ASM_mixerMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerOpen=ASM_mixerOpen")
#else
#pragma comment(linker, "/EXPORT:mixerOpen=_ASM_mixerOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mixerSetControlDetails=ASM_mixerSetControlDetails")
#else
#pragma comment(linker, "/EXPORT:mixerSetControlDetails=_ASM_mixerSetControlDetails@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmDrvInstall=ASM_mmDrvInstall")
#else
#pragma comment(linker, "/EXPORT:mmDrvInstall=_ASM_mmDrvInstall@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmGetCurrentTask=ASM_mmGetCurrentTask")
#else
#pragma comment(linker, "/EXPORT:mmGetCurrentTask=_ASM_mmGetCurrentTask@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmTaskBlock=ASM_mmTaskBlock")
#else
#pragma comment(linker, "/EXPORT:mmTaskBlock=_ASM_mmTaskBlock@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmTaskCreate=ASM_mmTaskCreate")
#else
#pragma comment(linker, "/EXPORT:mmTaskCreate=_ASM_mmTaskCreate@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmTaskSignal=ASM_mmTaskSignal")
#else
#pragma comment(linker, "/EXPORT:mmTaskSignal=_ASM_mmTaskSignal@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmTaskYield=ASM_mmTaskYield")
#else
#pragma comment(linker, "/EXPORT:mmTaskYield=_ASM_mmTaskYield@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioAdvance=ASM_mmioAdvance")
#else
#pragma comment(linker, "/EXPORT:mmioAdvance=_ASM_mmioAdvance@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioAscend=ASM_mmioAscend")
#else
#pragma comment(linker, "/EXPORT:mmioAscend=_ASM_mmioAscend@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioClose=ASM_mmioClose")
#else
#pragma comment(linker, "/EXPORT:mmioClose=_ASM_mmioClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioCreateChunk=ASM_mmioCreateChunk")
#else
#pragma comment(linker, "/EXPORT:mmioCreateChunk=_ASM_mmioCreateChunk@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioDescend=ASM_mmioDescend")
#else
#pragma comment(linker, "/EXPORT:mmioDescend=_ASM_mmioDescend@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioFlush=ASM_mmioFlush")
#else
#pragma comment(linker, "/EXPORT:mmioFlush=_ASM_mmioFlush@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioGetInfo=ASM_mmioGetInfo")
#else
#pragma comment(linker, "/EXPORT:mmioGetInfo=_ASM_mmioGetInfo@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioInstallIOProcA=ASM_mmioInstallIOProcA")
#else
#pragma comment(linker, "/EXPORT:mmioInstallIOProcA=_ASM_mmioInstallIOProcA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioInstallIOProcW=ASM_mmioInstallIOProcW")
#else
#pragma comment(linker, "/EXPORT:mmioInstallIOProcW=_ASM_mmioInstallIOProcW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioOpenA=ASM_mmioOpenA")
#else
#pragma comment(linker, "/EXPORT:mmioOpenA=_ASM_mmioOpenA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioOpenW=ASM_mmioOpenW")
#else
#pragma comment(linker, "/EXPORT:mmioOpenW=_ASM_mmioOpenW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioRead=ASM_mmioRead")
#else
#pragma comment(linker, "/EXPORT:mmioRead=_ASM_mmioRead@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioRenameA=ASM_mmioRenameA")
#else
#pragma comment(linker, "/EXPORT:mmioRenameA=_ASM_mmioRenameA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioRenameW=ASM_mmioRenameW")
#else
#pragma comment(linker, "/EXPORT:mmioRenameW=_ASM_mmioRenameW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioSeek=ASM_mmioSeek")
#else
#pragma comment(linker, "/EXPORT:mmioSeek=_ASM_mmioSeek@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioSendMessage=ASM_mmioSendMessage")
#else
#pragma comment(linker, "/EXPORT:mmioSendMessage=_ASM_mmioSendMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioSetBuffer=ASM_mmioSetBuffer")
#else
#pragma comment(linker, "/EXPORT:mmioSetBuffer=_ASM_mmioSetBuffer@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioSetInfo=ASM_mmioSetInfo")
#else
#pragma comment(linker, "/EXPORT:mmioSetInfo=_ASM_mmioSetInfo@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCA=ASM_mmioStringToFOURCCA")
#else
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCA=_ASM_mmioStringToFOURCCA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCW=ASM_mmioStringToFOURCCW")
#else
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCW=_ASM_mmioStringToFOURCCW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmioWrite=ASM_mmioWrite")
#else
#pragma comment(linker, "/EXPORT:mmioWrite=_ASM_mmioWrite@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:mmsystemGetVersion=ASM_mmsystemGetVersion")
#else
#pragma comment(linker, "/EXPORT:mmsystemGetVersion=_ASM_mmsystemGetVersion@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:sndPlaySoundA=ASM_sndPlaySoundA")
#else
#pragma comment(linker, "/EXPORT:sndPlaySoundA=_ASM_sndPlaySoundA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:sndPlaySoundW=ASM_sndPlaySoundW")
#else
#pragma comment(linker, "/EXPORT:sndPlaySoundW=_ASM_sndPlaySoundW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeBeginPeriod=ASM_timeBeginPeriod")
#else
#pragma comment(linker, "/EXPORT:timeBeginPeriod=_ASM_timeBeginPeriod@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeEndPeriod=ASM_timeEndPeriod")
#else
#pragma comment(linker, "/EXPORT:timeEndPeriod=_ASM_timeEndPeriod@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeGetDevCaps=ASM_timeGetDevCaps")
#else
#pragma comment(linker, "/EXPORT:timeGetDevCaps=_ASM_timeGetDevCaps@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeGetSystemTime=ASM_timeGetSystemTime")
#else
#pragma comment(linker, "/EXPORT:timeGetSystemTime=_ASM_timeGetSystemTime@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeGetTime=ASM_timeGetTime")
#else
#pragma comment(linker, "/EXPORT:timeGetTime=_ASM_timeGetTime@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeKillEvent=ASM_timeKillEvent")
#else
#pragma comment(linker, "/EXPORT:timeKillEvent=_ASM_timeKillEvent@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:timeSetEvent=ASM_timeSetEvent")
#else
#pragma comment(linker, "/EXPORT:timeSetEvent=_ASM_timeSetEvent@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInAddBuffer=ASM_waveInAddBuffer")
#else
#pragma comment(linker, "/EXPORT:waveInAddBuffer=_ASM_waveInAddBuffer@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInClose=ASM_waveInClose")
#else
#pragma comment(linker, "/EXPORT:waveInClose=_ASM_waveInClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetDevCapsA=ASM_waveInGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:waveInGetDevCapsA=_ASM_waveInGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetDevCapsW=ASM_waveInGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:waveInGetDevCapsW=_ASM_waveInGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetErrorTextA=ASM_waveInGetErrorTextA")
#else
#pragma comment(linker, "/EXPORT:waveInGetErrorTextA=_ASM_waveInGetErrorTextA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetErrorTextW=ASM_waveInGetErrorTextW")
#else
#pragma comment(linker, "/EXPORT:waveInGetErrorTextW=_ASM_waveInGetErrorTextW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetID=ASM_waveInGetID")
#else
#pragma comment(linker, "/EXPORT:waveInGetID=_ASM_waveInGetID@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetNumDevs=ASM_waveInGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:waveInGetNumDevs=_ASM_waveInGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInGetPosition=ASM_waveInGetPosition")
#else
#pragma comment(linker, "/EXPORT:waveInGetPosition=_ASM_waveInGetPosition@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInMessage=ASM_waveInMessage")
#else
#pragma comment(linker, "/EXPORT:waveInMessage=_ASM_waveInMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInOpen=ASM_waveInOpen")
#else
#pragma comment(linker, "/EXPORT:waveInOpen=_ASM_waveInOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInPrepareHeader=ASM_waveInPrepareHeader")
#else
#pragma comment(linker, "/EXPORT:waveInPrepareHeader=_ASM_waveInPrepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInReset=ASM_waveInReset")
#else
#pragma comment(linker, "/EXPORT:waveInReset=_ASM_waveInReset@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInStart=ASM_waveInStart")
#else
#pragma comment(linker, "/EXPORT:waveInStart=_ASM_waveInStart@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInStop=ASM_waveInStop")
#else
#pragma comment(linker, "/EXPORT:waveInStop=_ASM_waveInStop@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveInUnprepareHeader=ASM_waveInUnprepareHeader")
#else
#pragma comment(linker, "/EXPORT:waveInUnprepareHeader=_ASM_waveInUnprepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutBreakLoop=ASM_waveOutBreakLoop")
#else
#pragma comment(linker, "/EXPORT:waveOutBreakLoop=_ASM_waveOutBreakLoop@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutClose=ASM_waveOutClose")
#else
#pragma comment(linker, "/EXPORT:waveOutClose=_ASM_waveOutClose@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsA=ASM_waveOutGetDevCapsA")
#else
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsA=_ASM_waveOutGetDevCapsA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsW=ASM_waveOutGetDevCapsW")
#else
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsW=_ASM_waveOutGetDevCapsW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextA=ASM_waveOutGetErrorTextA")
#else
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextA=_ASM_waveOutGetErrorTextA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextW=ASM_waveOutGetErrorTextW")
#else
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextW=_ASM_waveOutGetErrorTextW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetID=ASM_waveOutGetID")
#else
#pragma comment(linker, "/EXPORT:waveOutGetID=_ASM_waveOutGetID@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetNumDevs=ASM_waveOutGetNumDevs")
#else
#pragma comment(linker, "/EXPORT:waveOutGetNumDevs=_ASM_waveOutGetNumDevs@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetPitch=ASM_waveOutGetPitch")
#else
#pragma comment(linker, "/EXPORT:waveOutGetPitch=_ASM_waveOutGetPitch@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetPlaybackRate=ASM_waveOutGetPlaybackRate")
#else
#pragma comment(linker, "/EXPORT:waveOutGetPlaybackRate=_ASM_waveOutGetPlaybackRate@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetPosition=ASM_waveOutGetPosition")
#else
#pragma comment(linker, "/EXPORT:waveOutGetPosition=_ASM_waveOutGetPosition@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutGetVolume=ASM_waveOutGetVolume")
#else
#pragma comment(linker, "/EXPORT:waveOutGetVolume=_ASM_waveOutGetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutMessage=ASM_waveOutMessage")
#else
#pragma comment(linker, "/EXPORT:waveOutMessage=_ASM_waveOutMessage@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutOpen=ASM_waveOutOpen")
#else
#pragma comment(linker, "/EXPORT:waveOutOpen=_ASM_waveOutOpen@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutPause=ASM_waveOutPause")
#else
#pragma comment(linker, "/EXPORT:waveOutPause=_ASM_waveOutPause@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutPrepareHeader=ASM_waveOutPrepareHeader")
#else
#pragma comment(linker, "/EXPORT:waveOutPrepareHeader=_ASM_waveOutPrepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutReset=ASM_waveOutReset")
#else
#pragma comment(linker, "/EXPORT:waveOutReset=_ASM_waveOutReset@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutRestart=ASM_waveOutRestart")
#else
#pragma comment(linker, "/EXPORT:waveOutRestart=_ASM_waveOutRestart@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutSetPitch=ASM_waveOutSetPitch")
#else
#pragma comment(linker, "/EXPORT:waveOutSetPitch=_ASM_waveOutSetPitch@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutSetPlaybackRate=ASM_waveOutSetPlaybackRate")
#else
#pragma comment(linker, "/EXPORT:waveOutSetPlaybackRate=_ASM_waveOutSetPlaybackRate@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutSetVolume=ASM_waveOutSetVolume")
#else
#pragma comment(linker, "/EXPORT:waveOutSetVolume=_ASM_waveOutSetVolume@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutUnprepareHeader=ASM_waveOutUnprepareHeader")
#else
#pragma comment(linker, "/EXPORT:waveOutUnprepareHeader=_ASM_waveOutUnprepareHeader@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:waveOutWrite=ASM_waveOutWrite")
#else
#pragma comment(linker, "/EXPORT:waveOutWrite=_ASM_waveOutWrite@8")
#endif

// bind native dll first
extern void GetOrignalLibraryPath(TCHAR* bufferPtr, int bufferLength, const TCHAR* libName);

void __CheckedLoad()
{
    TCHAR szPath[MAX_PATH];

    GetOrignalLibraryPath(szPath, MAX_PATH, TEXT("winmm.dll"));

    // if your dll is not in system path
    // please reset szPath here
    HMODULE module = LoadLibrary(szPath);

    if (module == NULL)
    {
        TCHAR szMessage[MAX_PATH];
        wsprintf(szMessage, TEXT("Failed load dll from:%s"), szPath);
        MessageBox(0, szMessage, TEXT("AHeadLib.Net Error"), 0);
        
        ExitProcess(1);
        return;
    }

    CloseDriverPtr = __CheckedGetFunction(module, "CloseDriver");
    DefDriverProcPtr = __CheckedGetFunction(module, "DefDriverProc");
    DriverCallbackPtr = __CheckedGetFunction(module, "DriverCallback");
    DrvGetModuleHandlePtr = __CheckedGetFunction(module, "DrvGetModuleHandle");
    GetDriverModuleHandlePtr = __CheckedGetFunction(module, "GetDriverModuleHandle");
    OpenDriverPtr = __CheckedGetFunction(module, "OpenDriver");
    PlaySoundPtr = __CheckedGetFunction(module, "PlaySound");
    PlaySoundAPtr = __CheckedGetFunction(module, "PlaySoundA");
    PlaySoundWPtr = __CheckedGetFunction(module, "PlaySoundW");
    SendDriverMessagePtr = __CheckedGetFunction(module, "SendDriverMessage");
    WOWAppExitPtr = __CheckedGetFunction(module, "WOWAppExit");
    auxGetDevCapsAPtr = __CheckedGetFunction(module, "auxGetDevCapsA");
    auxGetDevCapsWPtr = __CheckedGetFunction(module, "auxGetDevCapsW");
    auxGetNumDevsPtr = __CheckedGetFunction(module, "auxGetNumDevs");
    auxGetVolumePtr = __CheckedGetFunction(module, "auxGetVolume");
    auxOutMessagePtr = __CheckedGetFunction(module, "auxOutMessage");
    auxSetVolumePtr = __CheckedGetFunction(module, "auxSetVolume");
    joyConfigChangedPtr = __CheckedGetFunction(module, "joyConfigChanged");
    joyGetDevCapsAPtr = __CheckedGetFunction(module, "joyGetDevCapsA");
    joyGetDevCapsWPtr = __CheckedGetFunction(module, "joyGetDevCapsW");
    joyGetNumDevsPtr = __CheckedGetFunction(module, "joyGetNumDevs");
    joyGetPosPtr = __CheckedGetFunction(module, "joyGetPos");
    joyGetPosExPtr = __CheckedGetFunction(module, "joyGetPosEx");
    joyGetThresholdPtr = __CheckedGetFunction(module, "joyGetThreshold");
    joyReleaseCapturePtr = __CheckedGetFunction(module, "joyReleaseCapture");
    joySetCapturePtr = __CheckedGetFunction(module, "joySetCapture");
    joySetThresholdPtr = __CheckedGetFunction(module, "joySetThreshold");
    mciDriverNotifyPtr = __CheckedGetFunction(module, "mciDriverNotify");
    mciDriverYieldPtr = __CheckedGetFunction(module, "mciDriverYield");
    mciExecutePtr = __CheckedGetFunction(module, "mciExecute");
    mciFreeCommandResourcePtr = __CheckedGetFunction(module, "mciFreeCommandResource");
    mciGetCreatorTaskPtr = __CheckedGetFunction(module, "mciGetCreatorTask");
    mciGetDeviceIDAPtr = __CheckedGetFunction(module, "mciGetDeviceIDA");
    mciGetDeviceIDFromElementIDAPtr = __CheckedGetFunction(module, "mciGetDeviceIDFromElementIDA");
    mciGetDeviceIDFromElementIDWPtr = __CheckedGetFunction(module, "mciGetDeviceIDFromElementIDW");
    mciGetDeviceIDWPtr = __CheckedGetFunction(module, "mciGetDeviceIDW");
    mciGetDriverDataPtr = __CheckedGetFunction(module, "mciGetDriverData");
    mciGetErrorStringAPtr = __CheckedGetFunction(module, "mciGetErrorStringA");
    mciGetErrorStringWPtr = __CheckedGetFunction(module, "mciGetErrorStringW");
    mciGetYieldProcPtr = __CheckedGetFunction(module, "mciGetYieldProc");
    mciLoadCommandResourcePtr = __CheckedGetFunction(module, "mciLoadCommandResource");
    mciSendCommandAPtr = __CheckedGetFunction(module, "mciSendCommandA");
    mciSendCommandWPtr = __CheckedGetFunction(module, "mciSendCommandW");
    mciSendStringAPtr = __CheckedGetFunction(module, "mciSendStringA");
    mciSendStringWPtr = __CheckedGetFunction(module, "mciSendStringW");
    mciSetDriverDataPtr = __CheckedGetFunction(module, "mciSetDriverData");
    mciSetYieldProcPtr = __CheckedGetFunction(module, "mciSetYieldProc");
    midiConnectPtr = __CheckedGetFunction(module, "midiConnect");
    midiDisconnectPtr = __CheckedGetFunction(module, "midiDisconnect");
    midiInAddBufferPtr = __CheckedGetFunction(module, "midiInAddBuffer");
    midiInClosePtr = __CheckedGetFunction(module, "midiInClose");
    midiInGetDevCapsAPtr = __CheckedGetFunction(module, "midiInGetDevCapsA");
    midiInGetDevCapsWPtr = __CheckedGetFunction(module, "midiInGetDevCapsW");
    midiInGetErrorTextAPtr = __CheckedGetFunction(module, "midiInGetErrorTextA");
    midiInGetErrorTextWPtr = __CheckedGetFunction(module, "midiInGetErrorTextW");
    midiInGetIDPtr = __CheckedGetFunction(module, "midiInGetID");
    midiInGetNumDevsPtr = __CheckedGetFunction(module, "midiInGetNumDevs");
    midiInMessagePtr = __CheckedGetFunction(module, "midiInMessage");
    midiInOpenPtr = __CheckedGetFunction(module, "midiInOpen");
    midiInPrepareHeaderPtr = __CheckedGetFunction(module, "midiInPrepareHeader");
    midiInResetPtr = __CheckedGetFunction(module, "midiInReset");
    midiInStartPtr = __CheckedGetFunction(module, "midiInStart");
    midiInStopPtr = __CheckedGetFunction(module, "midiInStop");
    midiInUnprepareHeaderPtr = __CheckedGetFunction(module, "midiInUnprepareHeader");
    midiOutCacheDrumPatchesPtr = __CheckedGetFunction(module, "midiOutCacheDrumPatches");
    midiOutCachePatchesPtr = __CheckedGetFunction(module, "midiOutCachePatches");
    midiOutClosePtr = __CheckedGetFunction(module, "midiOutClose");
    midiOutGetDevCapsAPtr = __CheckedGetFunction(module, "midiOutGetDevCapsA");
    midiOutGetDevCapsWPtr = __CheckedGetFunction(module, "midiOutGetDevCapsW");
    midiOutGetErrorTextAPtr = __CheckedGetFunction(module, "midiOutGetErrorTextA");
    midiOutGetErrorTextWPtr = __CheckedGetFunction(module, "midiOutGetErrorTextW");
    midiOutGetIDPtr = __CheckedGetFunction(module, "midiOutGetID");
    midiOutGetNumDevsPtr = __CheckedGetFunction(module, "midiOutGetNumDevs");
    midiOutGetVolumePtr = __CheckedGetFunction(module, "midiOutGetVolume");
    midiOutLongMsgPtr = __CheckedGetFunction(module, "midiOutLongMsg");
    midiOutMessagePtr = __CheckedGetFunction(module, "midiOutMessage");
    midiOutOpenPtr = __CheckedGetFunction(module, "midiOutOpen");
    midiOutPrepareHeaderPtr = __CheckedGetFunction(module, "midiOutPrepareHeader");
    midiOutResetPtr = __CheckedGetFunction(module, "midiOutReset");
    midiOutSetVolumePtr = __CheckedGetFunction(module, "midiOutSetVolume");
    midiOutShortMsgPtr = __CheckedGetFunction(module, "midiOutShortMsg");
    midiOutUnprepareHeaderPtr = __CheckedGetFunction(module, "midiOutUnprepareHeader");
    midiStreamClosePtr = __CheckedGetFunction(module, "midiStreamClose");
    midiStreamOpenPtr = __CheckedGetFunction(module, "midiStreamOpen");
    midiStreamOutPtr = __CheckedGetFunction(module, "midiStreamOut");
    midiStreamPausePtr = __CheckedGetFunction(module, "midiStreamPause");
    midiStreamPositionPtr = __CheckedGetFunction(module, "midiStreamPosition");
    midiStreamPropertyPtr = __CheckedGetFunction(module, "midiStreamProperty");
    midiStreamRestartPtr = __CheckedGetFunction(module, "midiStreamRestart");
    midiStreamStopPtr = __CheckedGetFunction(module, "midiStreamStop");
    mixerClosePtr = __CheckedGetFunction(module, "mixerClose");
    mixerGetControlDetailsAPtr = __CheckedGetFunction(module, "mixerGetControlDetailsA");
    mixerGetControlDetailsWPtr = __CheckedGetFunction(module, "mixerGetControlDetailsW");
    mixerGetDevCapsAPtr = __CheckedGetFunction(module, "mixerGetDevCapsA");
    mixerGetDevCapsWPtr = __CheckedGetFunction(module, "mixerGetDevCapsW");
    mixerGetIDPtr = __CheckedGetFunction(module, "mixerGetID");
    mixerGetLineControlsAPtr = __CheckedGetFunction(module, "mixerGetLineControlsA");
    mixerGetLineControlsWPtr = __CheckedGetFunction(module, "mixerGetLineControlsW");
    mixerGetLineInfoAPtr = __CheckedGetFunction(module, "mixerGetLineInfoA");
    mixerGetLineInfoWPtr = __CheckedGetFunction(module, "mixerGetLineInfoW");
    mixerGetNumDevsPtr = __CheckedGetFunction(module, "mixerGetNumDevs");
    mixerMessagePtr = __CheckedGetFunction(module, "mixerMessage");
    mixerOpenPtr = __CheckedGetFunction(module, "mixerOpen");
    mixerSetControlDetailsPtr = __CheckedGetFunction(module, "mixerSetControlDetails");
    mmDrvInstallPtr = __CheckedGetFunction(module, "mmDrvInstall");
    mmGetCurrentTaskPtr = __CheckedGetFunction(module, "mmGetCurrentTask");
    mmTaskBlockPtr = __CheckedGetFunction(module, "mmTaskBlock");
    mmTaskCreatePtr = __CheckedGetFunction(module, "mmTaskCreate");
    mmTaskSignalPtr = __CheckedGetFunction(module, "mmTaskSignal");
    mmTaskYieldPtr = __CheckedGetFunction(module, "mmTaskYield");
    mmioAdvancePtr = __CheckedGetFunction(module, "mmioAdvance");
    mmioAscendPtr = __CheckedGetFunction(module, "mmioAscend");
    mmioClosePtr = __CheckedGetFunction(module, "mmioClose");
    mmioCreateChunkPtr = __CheckedGetFunction(module, "mmioCreateChunk");
    mmioDescendPtr = __CheckedGetFunction(module, "mmioDescend");
    mmioFlushPtr = __CheckedGetFunction(module, "mmioFlush");
    mmioGetInfoPtr = __CheckedGetFunction(module, "mmioGetInfo");
    mmioInstallIOProcAPtr = __CheckedGetFunction(module, "mmioInstallIOProcA");
    mmioInstallIOProcWPtr = __CheckedGetFunction(module, "mmioInstallIOProcW");
    mmioOpenAPtr = __CheckedGetFunction(module, "mmioOpenA");
    mmioOpenWPtr = __CheckedGetFunction(module, "mmioOpenW");
    mmioReadPtr = __CheckedGetFunction(module, "mmioRead");
    mmioRenameAPtr = __CheckedGetFunction(module, "mmioRenameA");
    mmioRenameWPtr = __CheckedGetFunction(module, "mmioRenameW");
    mmioSeekPtr = __CheckedGetFunction(module, "mmioSeek");
    mmioSendMessagePtr = __CheckedGetFunction(module, "mmioSendMessage");
    mmioSetBufferPtr = __CheckedGetFunction(module, "mmioSetBuffer");
    mmioSetInfoPtr = __CheckedGetFunction(module, "mmioSetInfo");
    mmioStringToFOURCCAPtr = __CheckedGetFunction(module, "mmioStringToFOURCCA");
    mmioStringToFOURCCWPtr = __CheckedGetFunction(module, "mmioStringToFOURCCW");
    mmioWritePtr = __CheckedGetFunction(module, "mmioWrite");
    mmsystemGetVersionPtr = __CheckedGetFunction(module, "mmsystemGetVersion");
    sndPlaySoundAPtr = __CheckedGetFunction(module, "sndPlaySoundA");
    sndPlaySoundWPtr = __CheckedGetFunction(module, "sndPlaySoundW");
    timeBeginPeriodPtr = __CheckedGetFunction(module, "timeBeginPeriod");
    timeEndPeriodPtr = __CheckedGetFunction(module, "timeEndPeriod");
    timeGetDevCapsPtr = __CheckedGetFunction(module, "timeGetDevCaps");
    timeGetSystemTimePtr = __CheckedGetFunction(module, "timeGetSystemTime");
    timeGetTimePtr = __CheckedGetFunction(module, "timeGetTime");
    timeKillEventPtr = __CheckedGetFunction(module, "timeKillEvent");
    timeSetEventPtr = __CheckedGetFunction(module, "timeSetEvent");
    waveInAddBufferPtr = __CheckedGetFunction(module, "waveInAddBuffer");
    waveInClosePtr = __CheckedGetFunction(module, "waveInClose");
    waveInGetDevCapsAPtr = __CheckedGetFunction(module, "waveInGetDevCapsA");
    waveInGetDevCapsWPtr = __CheckedGetFunction(module, "waveInGetDevCapsW");
    waveInGetErrorTextAPtr = __CheckedGetFunction(module, "waveInGetErrorTextA");
    waveInGetErrorTextWPtr = __CheckedGetFunction(module, "waveInGetErrorTextW");
    waveInGetIDPtr = __CheckedGetFunction(module, "waveInGetID");
    waveInGetNumDevsPtr = __CheckedGetFunction(module, "waveInGetNumDevs");
    waveInGetPositionPtr = __CheckedGetFunction(module, "waveInGetPosition");
    waveInMessagePtr = __CheckedGetFunction(module, "waveInMessage");
    waveInOpenPtr = __CheckedGetFunction(module, "waveInOpen");
    waveInPrepareHeaderPtr = __CheckedGetFunction(module, "waveInPrepareHeader");
    waveInResetPtr = __CheckedGetFunction(module, "waveInReset");
    waveInStartPtr = __CheckedGetFunction(module, "waveInStart");
    waveInStopPtr = __CheckedGetFunction(module, "waveInStop");
    waveInUnprepareHeaderPtr = __CheckedGetFunction(module, "waveInUnprepareHeader");
    waveOutBreakLoopPtr = __CheckedGetFunction(module, "waveOutBreakLoop");
    waveOutClosePtr = __CheckedGetFunction(module, "waveOutClose");
    waveOutGetDevCapsAPtr = __CheckedGetFunction(module, "waveOutGetDevCapsA");
    waveOutGetDevCapsWPtr = __CheckedGetFunction(module, "waveOutGetDevCapsW");
    waveOutGetErrorTextAPtr = __CheckedGetFunction(module, "waveOutGetErrorTextA");
    waveOutGetErrorTextWPtr = __CheckedGetFunction(module, "waveOutGetErrorTextW");
    waveOutGetIDPtr = __CheckedGetFunction(module, "waveOutGetID");
    waveOutGetNumDevsPtr = __CheckedGetFunction(module, "waveOutGetNumDevs");
    waveOutGetPitchPtr = __CheckedGetFunction(module, "waveOutGetPitch");
    waveOutGetPlaybackRatePtr = __CheckedGetFunction(module, "waveOutGetPlaybackRate");
    waveOutGetPositionPtr = __CheckedGetFunction(module, "waveOutGetPosition");
    waveOutGetVolumePtr = __CheckedGetFunction(module, "waveOutGetVolume");
    waveOutMessagePtr = __CheckedGetFunction(module, "waveOutMessage");
    waveOutOpenPtr = __CheckedGetFunction(module, "waveOutOpen");
    waveOutPausePtr = __CheckedGetFunction(module, "waveOutPause");
    waveOutPrepareHeaderPtr = __CheckedGetFunction(module, "waveOutPrepareHeader");
    waveOutResetPtr = __CheckedGetFunction(module, "waveOutReset");
    waveOutRestartPtr = __CheckedGetFunction(module, "waveOutRestart");
    waveOutSetPitchPtr = __CheckedGetFunction(module, "waveOutSetPitch");
    waveOutSetPlaybackRatePtr = __CheckedGetFunction(module, "waveOutSetPlaybackRate");
    waveOutSetVolumePtr = __CheckedGetFunction(module, "waveOutSetVolume");
    waveOutUnprepareHeaderPtr = __CheckedGetFunction(module, "waveOutUnprepareHeader");
    waveOutWritePtr = __CheckedGetFunction(module, "waveOutWrite");
}


