; generated by tools
; AHeadLib.Net
; https://github.com/bodong1987/AHeadLib.Net
; Powered by bodong

.MODEL FLAT

.DATA
    EXTERNDEF _CloseDriverPtr:DWORD
    EXTERNDEF _DefDriverProcPtr:DWORD
    EXTERNDEF _DriverCallbackPtr:DWORD
    EXTERNDEF _DrvGetModuleHandlePtr:DWORD
    EXTERNDEF _GetDriverModuleHandlePtr:DWORD
    EXTERNDEF _OpenDriverPtr:DWORD
    EXTERNDEF _PlaySoundPtr:DWORD
    EXTERNDEF _PlaySoundAPtr:DWORD
    EXTERNDEF _PlaySoundWPtr:DWORD
    EXTERNDEF _SendDriverMessagePtr:DWORD
    EXTERNDEF _WOWAppExitPtr:DWORD
    EXTERNDEF _auxGetDevCapsAPtr:DWORD
    EXTERNDEF _auxGetDevCapsWPtr:DWORD
    EXTERNDEF _auxGetNumDevsPtr:DWORD
    EXTERNDEF _auxGetVolumePtr:DWORD
    EXTERNDEF _auxOutMessagePtr:DWORD
    EXTERNDEF _auxSetVolumePtr:DWORD
    EXTERNDEF _joyConfigChangedPtr:DWORD
    EXTERNDEF _joyGetDevCapsAPtr:DWORD
    EXTERNDEF _joyGetDevCapsWPtr:DWORD
    EXTERNDEF _joyGetNumDevsPtr:DWORD
    EXTERNDEF _joyGetPosPtr:DWORD
    EXTERNDEF _joyGetPosExPtr:DWORD
    EXTERNDEF _joyGetThresholdPtr:DWORD
    EXTERNDEF _joyReleaseCapturePtr:DWORD
    EXTERNDEF _joySetCapturePtr:DWORD
    EXTERNDEF _joySetThresholdPtr:DWORD
    EXTERNDEF _mciDriverNotifyPtr:DWORD
    EXTERNDEF _mciDriverYieldPtr:DWORD
    EXTERNDEF _mciExecutePtr:DWORD
    EXTERNDEF _mciFreeCommandResourcePtr:DWORD
    EXTERNDEF _mciGetCreatorTaskPtr:DWORD
    EXTERNDEF _mciGetDeviceIDAPtr:DWORD
    EXTERNDEF _mciGetDeviceIDFromElementIDAPtr:DWORD
    EXTERNDEF _mciGetDeviceIDFromElementIDWPtr:DWORD
    EXTERNDEF _mciGetDeviceIDWPtr:DWORD
    EXTERNDEF _mciGetDriverDataPtr:DWORD
    EXTERNDEF _mciGetErrorStringAPtr:DWORD
    EXTERNDEF _mciGetErrorStringWPtr:DWORD
    EXTERNDEF _mciGetYieldProcPtr:DWORD
    EXTERNDEF _mciLoadCommandResourcePtr:DWORD
    EXTERNDEF _mciSendCommandAPtr:DWORD
    EXTERNDEF _mciSendCommandWPtr:DWORD
    EXTERNDEF _mciSendStringAPtr:DWORD
    EXTERNDEF _mciSendStringWPtr:DWORD
    EXTERNDEF _mciSetDriverDataPtr:DWORD
    EXTERNDEF _mciSetYieldProcPtr:DWORD
    EXTERNDEF _midiConnectPtr:DWORD
    EXTERNDEF _midiDisconnectPtr:DWORD
    EXTERNDEF _midiInAddBufferPtr:DWORD
    EXTERNDEF _midiInClosePtr:DWORD
    EXTERNDEF _midiInGetDevCapsAPtr:DWORD
    EXTERNDEF _midiInGetDevCapsWPtr:DWORD
    EXTERNDEF _midiInGetErrorTextAPtr:DWORD
    EXTERNDEF _midiInGetErrorTextWPtr:DWORD
    EXTERNDEF _midiInGetIDPtr:DWORD
    EXTERNDEF _midiInGetNumDevsPtr:DWORD
    EXTERNDEF _midiInMessagePtr:DWORD
    EXTERNDEF _midiInOpenPtr:DWORD
    EXTERNDEF _midiInPrepareHeaderPtr:DWORD
    EXTERNDEF _midiInResetPtr:DWORD
    EXTERNDEF _midiInStartPtr:DWORD
    EXTERNDEF _midiInStopPtr:DWORD
    EXTERNDEF _midiInUnprepareHeaderPtr:DWORD
    EXTERNDEF _midiOutCacheDrumPatchesPtr:DWORD
    EXTERNDEF _midiOutCachePatchesPtr:DWORD
    EXTERNDEF _midiOutClosePtr:DWORD
    EXTERNDEF _midiOutGetDevCapsAPtr:DWORD
    EXTERNDEF _midiOutGetDevCapsWPtr:DWORD
    EXTERNDEF _midiOutGetErrorTextAPtr:DWORD
    EXTERNDEF _midiOutGetErrorTextWPtr:DWORD
    EXTERNDEF _midiOutGetIDPtr:DWORD
    EXTERNDEF _midiOutGetNumDevsPtr:DWORD
    EXTERNDEF _midiOutGetVolumePtr:DWORD
    EXTERNDEF _midiOutLongMsgPtr:DWORD
    EXTERNDEF _midiOutMessagePtr:DWORD
    EXTERNDEF _midiOutOpenPtr:DWORD
    EXTERNDEF _midiOutPrepareHeaderPtr:DWORD
    EXTERNDEF _midiOutResetPtr:DWORD
    EXTERNDEF _midiOutSetVolumePtr:DWORD
    EXTERNDEF _midiOutShortMsgPtr:DWORD
    EXTERNDEF _midiOutUnprepareHeaderPtr:DWORD
    EXTERNDEF _midiStreamClosePtr:DWORD
    EXTERNDEF _midiStreamOpenPtr:DWORD
    EXTERNDEF _midiStreamOutPtr:DWORD
    EXTERNDEF _midiStreamPausePtr:DWORD
    EXTERNDEF _midiStreamPositionPtr:DWORD
    EXTERNDEF _midiStreamPropertyPtr:DWORD
    EXTERNDEF _midiStreamRestartPtr:DWORD
    EXTERNDEF _midiStreamStopPtr:DWORD
    EXTERNDEF _mixerClosePtr:DWORD
    EXTERNDEF _mixerGetControlDetailsAPtr:DWORD
    EXTERNDEF _mixerGetControlDetailsWPtr:DWORD
    EXTERNDEF _mixerGetDevCapsAPtr:DWORD
    EXTERNDEF _mixerGetDevCapsWPtr:DWORD
    EXTERNDEF _mixerGetIDPtr:DWORD
    EXTERNDEF _mixerGetLineControlsAPtr:DWORD
    EXTERNDEF _mixerGetLineControlsWPtr:DWORD
    EXTERNDEF _mixerGetLineInfoAPtr:DWORD
    EXTERNDEF _mixerGetLineInfoWPtr:DWORD
    EXTERNDEF _mixerGetNumDevsPtr:DWORD
    EXTERNDEF _mixerMessagePtr:DWORD
    EXTERNDEF _mixerOpenPtr:DWORD
    EXTERNDEF _mixerSetControlDetailsPtr:DWORD
    EXTERNDEF _mmDrvInstallPtr:DWORD
    EXTERNDEF _mmGetCurrentTaskPtr:DWORD
    EXTERNDEF _mmTaskBlockPtr:DWORD
    EXTERNDEF _mmTaskCreatePtr:DWORD
    EXTERNDEF _mmTaskSignalPtr:DWORD
    EXTERNDEF _mmTaskYieldPtr:DWORD
    EXTERNDEF _mmioAdvancePtr:DWORD
    EXTERNDEF _mmioAscendPtr:DWORD
    EXTERNDEF _mmioClosePtr:DWORD
    EXTERNDEF _mmioCreateChunkPtr:DWORD
    EXTERNDEF _mmioDescendPtr:DWORD
    EXTERNDEF _mmioFlushPtr:DWORD
    EXTERNDEF _mmioGetInfoPtr:DWORD
    EXTERNDEF _mmioInstallIOProcAPtr:DWORD
    EXTERNDEF _mmioInstallIOProcWPtr:DWORD
    EXTERNDEF _mmioOpenAPtr:DWORD
    EXTERNDEF _mmioOpenWPtr:DWORD
    EXTERNDEF _mmioReadPtr:DWORD
    EXTERNDEF _mmioRenameAPtr:DWORD
    EXTERNDEF _mmioRenameWPtr:DWORD
    EXTERNDEF _mmioSeekPtr:DWORD
    EXTERNDEF _mmioSendMessagePtr:DWORD
    EXTERNDEF _mmioSetBufferPtr:DWORD
    EXTERNDEF _mmioSetInfoPtr:DWORD
    EXTERNDEF _mmioStringToFOURCCAPtr:DWORD
    EXTERNDEF _mmioStringToFOURCCWPtr:DWORD
    EXTERNDEF _mmioWritePtr:DWORD
    EXTERNDEF _mmsystemGetVersionPtr:DWORD
    EXTERNDEF _sndPlaySoundAPtr:DWORD
    EXTERNDEF _sndPlaySoundWPtr:DWORD
    EXTERNDEF _timeBeginPeriodPtr:DWORD
    EXTERNDEF _timeEndPeriodPtr:DWORD
    EXTERNDEF _timeGetDevCapsPtr:DWORD
    EXTERNDEF _timeGetSystemTimePtr:DWORD
    EXTERNDEF _timeGetTimePtr:DWORD
    EXTERNDEF _timeKillEventPtr:DWORD
    EXTERNDEF _timeSetEventPtr:DWORD
    EXTERNDEF _waveInAddBufferPtr:DWORD
    EXTERNDEF _waveInClosePtr:DWORD
    EXTERNDEF _waveInGetDevCapsAPtr:DWORD
    EXTERNDEF _waveInGetDevCapsWPtr:DWORD
    EXTERNDEF _waveInGetErrorTextAPtr:DWORD
    EXTERNDEF _waveInGetErrorTextWPtr:DWORD
    EXTERNDEF _waveInGetIDPtr:DWORD
    EXTERNDEF _waveInGetNumDevsPtr:DWORD
    EXTERNDEF _waveInGetPositionPtr:DWORD
    EXTERNDEF _waveInMessagePtr:DWORD
    EXTERNDEF _waveInOpenPtr:DWORD
    EXTERNDEF _waveInPrepareHeaderPtr:DWORD
    EXTERNDEF _waveInResetPtr:DWORD
    EXTERNDEF _waveInStartPtr:DWORD
    EXTERNDEF _waveInStopPtr:DWORD
    EXTERNDEF _waveInUnprepareHeaderPtr:DWORD
    EXTERNDEF _waveOutBreakLoopPtr:DWORD
    EXTERNDEF _waveOutClosePtr:DWORD
    EXTERNDEF _waveOutGetDevCapsAPtr:DWORD
    EXTERNDEF _waveOutGetDevCapsWPtr:DWORD
    EXTERNDEF _waveOutGetErrorTextAPtr:DWORD
    EXTERNDEF _waveOutGetErrorTextWPtr:DWORD
    EXTERNDEF _waveOutGetIDPtr:DWORD
    EXTERNDEF _waveOutGetNumDevsPtr:DWORD
    EXTERNDEF _waveOutGetPitchPtr:DWORD
    EXTERNDEF _waveOutGetPlaybackRatePtr:DWORD
    EXTERNDEF _waveOutGetPositionPtr:DWORD
    EXTERNDEF _waveOutGetVolumePtr:DWORD
    EXTERNDEF _waveOutMessagePtr:DWORD
    EXTERNDEF _waveOutOpenPtr:DWORD
    EXTERNDEF _waveOutPausePtr:DWORD
    EXTERNDEF _waveOutPrepareHeaderPtr:DWORD
    EXTERNDEF _waveOutResetPtr:DWORD
    EXTERNDEF _waveOutRestartPtr:DWORD
    EXTERNDEF _waveOutSetPitchPtr:DWORD
    EXTERNDEF _waveOutSetPlaybackRatePtr:DWORD
    EXTERNDEF _waveOutSetVolumePtr:DWORD
    EXTERNDEF _waveOutUnprepareHeaderPtr:DWORD
    EXTERNDEF _waveOutWritePtr:DWORD

.CODE

_ASM_CloseDriver@8 PROC
    jmp DWORD PTR [_CloseDriverPtr]
_ASM_CloseDriver@8 ENDP

_ASM_DefDriverProc@8 PROC
    jmp DWORD PTR [_DefDriverProcPtr]
_ASM_DefDriverProc@8 ENDP

_ASM_DriverCallback@8 PROC
    jmp DWORD PTR [_DriverCallbackPtr]
_ASM_DriverCallback@8 ENDP

_ASM_DrvGetModuleHandle@8 PROC
    jmp DWORD PTR [_DrvGetModuleHandlePtr]
_ASM_DrvGetModuleHandle@8 ENDP

_ASM_GetDriverModuleHandle@8 PROC
    jmp DWORD PTR [_GetDriverModuleHandlePtr]
_ASM_GetDriverModuleHandle@8 ENDP

_ASM_OpenDriver@8 PROC
    jmp DWORD PTR [_OpenDriverPtr]
_ASM_OpenDriver@8 ENDP

_ASM_PlaySound@8 PROC
    jmp DWORD PTR [_PlaySoundPtr]
_ASM_PlaySound@8 ENDP

_ASM_PlaySoundA@8 PROC
    jmp DWORD PTR [_PlaySoundAPtr]
_ASM_PlaySoundA@8 ENDP

_ASM_PlaySoundW@8 PROC
    jmp DWORD PTR [_PlaySoundWPtr]
_ASM_PlaySoundW@8 ENDP

_ASM_SendDriverMessage@8 PROC
    jmp DWORD PTR [_SendDriverMessagePtr]
_ASM_SendDriverMessage@8 ENDP

_ASM_WOWAppExit@8 PROC
    jmp DWORD PTR [_WOWAppExitPtr]
_ASM_WOWAppExit@8 ENDP

_ASM_auxGetDevCapsA@8 PROC
    jmp DWORD PTR [_auxGetDevCapsAPtr]
_ASM_auxGetDevCapsA@8 ENDP

_ASM_auxGetDevCapsW@8 PROC
    jmp DWORD PTR [_auxGetDevCapsWPtr]
_ASM_auxGetDevCapsW@8 ENDP

_ASM_auxGetNumDevs@8 PROC
    jmp DWORD PTR [_auxGetNumDevsPtr]
_ASM_auxGetNumDevs@8 ENDP

_ASM_auxGetVolume@8 PROC
    jmp DWORD PTR [_auxGetVolumePtr]
_ASM_auxGetVolume@8 ENDP

_ASM_auxOutMessage@8 PROC
    jmp DWORD PTR [_auxOutMessagePtr]
_ASM_auxOutMessage@8 ENDP

_ASM_auxSetVolume@8 PROC
    jmp DWORD PTR [_auxSetVolumePtr]
_ASM_auxSetVolume@8 ENDP

_ASM_joyConfigChanged@8 PROC
    jmp DWORD PTR [_joyConfigChangedPtr]
_ASM_joyConfigChanged@8 ENDP

_ASM_joyGetDevCapsA@8 PROC
    jmp DWORD PTR [_joyGetDevCapsAPtr]
_ASM_joyGetDevCapsA@8 ENDP

_ASM_joyGetDevCapsW@8 PROC
    jmp DWORD PTR [_joyGetDevCapsWPtr]
_ASM_joyGetDevCapsW@8 ENDP

_ASM_joyGetNumDevs@8 PROC
    jmp DWORD PTR [_joyGetNumDevsPtr]
_ASM_joyGetNumDevs@8 ENDP

_ASM_joyGetPos@8 PROC
    jmp DWORD PTR [_joyGetPosPtr]
_ASM_joyGetPos@8 ENDP

_ASM_joyGetPosEx@8 PROC
    jmp DWORD PTR [_joyGetPosExPtr]
_ASM_joyGetPosEx@8 ENDP

_ASM_joyGetThreshold@8 PROC
    jmp DWORD PTR [_joyGetThresholdPtr]
_ASM_joyGetThreshold@8 ENDP

_ASM_joyReleaseCapture@8 PROC
    jmp DWORD PTR [_joyReleaseCapturePtr]
_ASM_joyReleaseCapture@8 ENDP

_ASM_joySetCapture@8 PROC
    jmp DWORD PTR [_joySetCapturePtr]
_ASM_joySetCapture@8 ENDP

_ASM_joySetThreshold@8 PROC
    jmp DWORD PTR [_joySetThresholdPtr]
_ASM_joySetThreshold@8 ENDP

_ASM_mciDriverNotify@8 PROC
    jmp DWORD PTR [_mciDriverNotifyPtr]
_ASM_mciDriverNotify@8 ENDP

_ASM_mciDriverYield@8 PROC
    jmp DWORD PTR [_mciDriverYieldPtr]
_ASM_mciDriverYield@8 ENDP

_ASM_mciExecute@8 PROC
    jmp DWORD PTR [_mciExecutePtr]
_ASM_mciExecute@8 ENDP

_ASM_mciFreeCommandResource@8 PROC
    jmp DWORD PTR [_mciFreeCommandResourcePtr]
_ASM_mciFreeCommandResource@8 ENDP

_ASM_mciGetCreatorTask@8 PROC
    jmp DWORD PTR [_mciGetCreatorTaskPtr]
_ASM_mciGetCreatorTask@8 ENDP

_ASM_mciGetDeviceIDA@8 PROC
    jmp DWORD PTR [_mciGetDeviceIDAPtr]
_ASM_mciGetDeviceIDA@8 ENDP

_ASM_mciGetDeviceIDFromElementIDA@8 PROC
    jmp DWORD PTR [_mciGetDeviceIDFromElementIDAPtr]
_ASM_mciGetDeviceIDFromElementIDA@8 ENDP

_ASM_mciGetDeviceIDFromElementIDW@8 PROC
    jmp DWORD PTR [_mciGetDeviceIDFromElementIDWPtr]
_ASM_mciGetDeviceIDFromElementIDW@8 ENDP

_ASM_mciGetDeviceIDW@8 PROC
    jmp DWORD PTR [_mciGetDeviceIDWPtr]
_ASM_mciGetDeviceIDW@8 ENDP

_ASM_mciGetDriverData@8 PROC
    jmp DWORD PTR [_mciGetDriverDataPtr]
_ASM_mciGetDriverData@8 ENDP

_ASM_mciGetErrorStringA@8 PROC
    jmp DWORD PTR [_mciGetErrorStringAPtr]
_ASM_mciGetErrorStringA@8 ENDP

_ASM_mciGetErrorStringW@8 PROC
    jmp DWORD PTR [_mciGetErrorStringWPtr]
_ASM_mciGetErrorStringW@8 ENDP

_ASM_mciGetYieldProc@8 PROC
    jmp DWORD PTR [_mciGetYieldProcPtr]
_ASM_mciGetYieldProc@8 ENDP

_ASM_mciLoadCommandResource@8 PROC
    jmp DWORD PTR [_mciLoadCommandResourcePtr]
_ASM_mciLoadCommandResource@8 ENDP

_ASM_mciSendCommandA@8 PROC
    jmp DWORD PTR [_mciSendCommandAPtr]
_ASM_mciSendCommandA@8 ENDP

_ASM_mciSendCommandW@8 PROC
    jmp DWORD PTR [_mciSendCommandWPtr]
_ASM_mciSendCommandW@8 ENDP

_ASM_mciSendStringA@8 PROC
    jmp DWORD PTR [_mciSendStringAPtr]
_ASM_mciSendStringA@8 ENDP

_ASM_mciSendStringW@8 PROC
    jmp DWORD PTR [_mciSendStringWPtr]
_ASM_mciSendStringW@8 ENDP

_ASM_mciSetDriverData@8 PROC
    jmp DWORD PTR [_mciSetDriverDataPtr]
_ASM_mciSetDriverData@8 ENDP

_ASM_mciSetYieldProc@8 PROC
    jmp DWORD PTR [_mciSetYieldProcPtr]
_ASM_mciSetYieldProc@8 ENDP

_ASM_midiConnect@8 PROC
    jmp DWORD PTR [_midiConnectPtr]
_ASM_midiConnect@8 ENDP

_ASM_midiDisconnect@8 PROC
    jmp DWORD PTR [_midiDisconnectPtr]
_ASM_midiDisconnect@8 ENDP

_ASM_midiInAddBuffer@8 PROC
    jmp DWORD PTR [_midiInAddBufferPtr]
_ASM_midiInAddBuffer@8 ENDP

_ASM_midiInClose@8 PROC
    jmp DWORD PTR [_midiInClosePtr]
_ASM_midiInClose@8 ENDP

_ASM_midiInGetDevCapsA@8 PROC
    jmp DWORD PTR [_midiInGetDevCapsAPtr]
_ASM_midiInGetDevCapsA@8 ENDP

_ASM_midiInGetDevCapsW@8 PROC
    jmp DWORD PTR [_midiInGetDevCapsWPtr]
_ASM_midiInGetDevCapsW@8 ENDP

_ASM_midiInGetErrorTextA@8 PROC
    jmp DWORD PTR [_midiInGetErrorTextAPtr]
_ASM_midiInGetErrorTextA@8 ENDP

_ASM_midiInGetErrorTextW@8 PROC
    jmp DWORD PTR [_midiInGetErrorTextWPtr]
_ASM_midiInGetErrorTextW@8 ENDP

_ASM_midiInGetID@8 PROC
    jmp DWORD PTR [_midiInGetIDPtr]
_ASM_midiInGetID@8 ENDP

_ASM_midiInGetNumDevs@8 PROC
    jmp DWORD PTR [_midiInGetNumDevsPtr]
_ASM_midiInGetNumDevs@8 ENDP

_ASM_midiInMessage@8 PROC
    jmp DWORD PTR [_midiInMessagePtr]
_ASM_midiInMessage@8 ENDP

_ASM_midiInOpen@8 PROC
    jmp DWORD PTR [_midiInOpenPtr]
_ASM_midiInOpen@8 ENDP

_ASM_midiInPrepareHeader@8 PROC
    jmp DWORD PTR [_midiInPrepareHeaderPtr]
_ASM_midiInPrepareHeader@8 ENDP

_ASM_midiInReset@8 PROC
    jmp DWORD PTR [_midiInResetPtr]
_ASM_midiInReset@8 ENDP

_ASM_midiInStart@8 PROC
    jmp DWORD PTR [_midiInStartPtr]
_ASM_midiInStart@8 ENDP

_ASM_midiInStop@8 PROC
    jmp DWORD PTR [_midiInStopPtr]
_ASM_midiInStop@8 ENDP

_ASM_midiInUnprepareHeader@8 PROC
    jmp DWORD PTR [_midiInUnprepareHeaderPtr]
_ASM_midiInUnprepareHeader@8 ENDP

_ASM_midiOutCacheDrumPatches@8 PROC
    jmp DWORD PTR [_midiOutCacheDrumPatchesPtr]
_ASM_midiOutCacheDrumPatches@8 ENDP

_ASM_midiOutCachePatches@8 PROC
    jmp DWORD PTR [_midiOutCachePatchesPtr]
_ASM_midiOutCachePatches@8 ENDP

_ASM_midiOutClose@8 PROC
    jmp DWORD PTR [_midiOutClosePtr]
_ASM_midiOutClose@8 ENDP

_ASM_midiOutGetDevCapsA@8 PROC
    jmp DWORD PTR [_midiOutGetDevCapsAPtr]
_ASM_midiOutGetDevCapsA@8 ENDP

_ASM_midiOutGetDevCapsW@8 PROC
    jmp DWORD PTR [_midiOutGetDevCapsWPtr]
_ASM_midiOutGetDevCapsW@8 ENDP

_ASM_midiOutGetErrorTextA@8 PROC
    jmp DWORD PTR [_midiOutGetErrorTextAPtr]
_ASM_midiOutGetErrorTextA@8 ENDP

_ASM_midiOutGetErrorTextW@8 PROC
    jmp DWORD PTR [_midiOutGetErrorTextWPtr]
_ASM_midiOutGetErrorTextW@8 ENDP

_ASM_midiOutGetID@8 PROC
    jmp DWORD PTR [_midiOutGetIDPtr]
_ASM_midiOutGetID@8 ENDP

_ASM_midiOutGetNumDevs@8 PROC
    jmp DWORD PTR [_midiOutGetNumDevsPtr]
_ASM_midiOutGetNumDevs@8 ENDP

_ASM_midiOutGetVolume@8 PROC
    jmp DWORD PTR [_midiOutGetVolumePtr]
_ASM_midiOutGetVolume@8 ENDP

_ASM_midiOutLongMsg@8 PROC
    jmp DWORD PTR [_midiOutLongMsgPtr]
_ASM_midiOutLongMsg@8 ENDP

_ASM_midiOutMessage@8 PROC
    jmp DWORD PTR [_midiOutMessagePtr]
_ASM_midiOutMessage@8 ENDP

_ASM_midiOutOpen@8 PROC
    jmp DWORD PTR [_midiOutOpenPtr]
_ASM_midiOutOpen@8 ENDP

_ASM_midiOutPrepareHeader@8 PROC
    jmp DWORD PTR [_midiOutPrepareHeaderPtr]
_ASM_midiOutPrepareHeader@8 ENDP

_ASM_midiOutReset@8 PROC
    jmp DWORD PTR [_midiOutResetPtr]
_ASM_midiOutReset@8 ENDP

_ASM_midiOutSetVolume@8 PROC
    jmp DWORD PTR [_midiOutSetVolumePtr]
_ASM_midiOutSetVolume@8 ENDP

_ASM_midiOutShortMsg@8 PROC
    jmp DWORD PTR [_midiOutShortMsgPtr]
_ASM_midiOutShortMsg@8 ENDP

_ASM_midiOutUnprepareHeader@8 PROC
    jmp DWORD PTR [_midiOutUnprepareHeaderPtr]
_ASM_midiOutUnprepareHeader@8 ENDP

_ASM_midiStreamClose@8 PROC
    jmp DWORD PTR [_midiStreamClosePtr]
_ASM_midiStreamClose@8 ENDP

_ASM_midiStreamOpen@8 PROC
    jmp DWORD PTR [_midiStreamOpenPtr]
_ASM_midiStreamOpen@8 ENDP

_ASM_midiStreamOut@8 PROC
    jmp DWORD PTR [_midiStreamOutPtr]
_ASM_midiStreamOut@8 ENDP

_ASM_midiStreamPause@8 PROC
    jmp DWORD PTR [_midiStreamPausePtr]
_ASM_midiStreamPause@8 ENDP

_ASM_midiStreamPosition@8 PROC
    jmp DWORD PTR [_midiStreamPositionPtr]
_ASM_midiStreamPosition@8 ENDP

_ASM_midiStreamProperty@8 PROC
    jmp DWORD PTR [_midiStreamPropertyPtr]
_ASM_midiStreamProperty@8 ENDP

_ASM_midiStreamRestart@8 PROC
    jmp DWORD PTR [_midiStreamRestartPtr]
_ASM_midiStreamRestart@8 ENDP

_ASM_midiStreamStop@8 PROC
    jmp DWORD PTR [_midiStreamStopPtr]
_ASM_midiStreamStop@8 ENDP

_ASM_mixerClose@8 PROC
    jmp DWORD PTR [_mixerClosePtr]
_ASM_mixerClose@8 ENDP

_ASM_mixerGetControlDetailsA@8 PROC
    jmp DWORD PTR [_mixerGetControlDetailsAPtr]
_ASM_mixerGetControlDetailsA@8 ENDP

_ASM_mixerGetControlDetailsW@8 PROC
    jmp DWORD PTR [_mixerGetControlDetailsWPtr]
_ASM_mixerGetControlDetailsW@8 ENDP

_ASM_mixerGetDevCapsA@8 PROC
    jmp DWORD PTR [_mixerGetDevCapsAPtr]
_ASM_mixerGetDevCapsA@8 ENDP

_ASM_mixerGetDevCapsW@8 PROC
    jmp DWORD PTR [_mixerGetDevCapsWPtr]
_ASM_mixerGetDevCapsW@8 ENDP

_ASM_mixerGetID@8 PROC
    jmp DWORD PTR [_mixerGetIDPtr]
_ASM_mixerGetID@8 ENDP

_ASM_mixerGetLineControlsA@8 PROC
    jmp DWORD PTR [_mixerGetLineControlsAPtr]
_ASM_mixerGetLineControlsA@8 ENDP

_ASM_mixerGetLineControlsW@8 PROC
    jmp DWORD PTR [_mixerGetLineControlsWPtr]
_ASM_mixerGetLineControlsW@8 ENDP

_ASM_mixerGetLineInfoA@8 PROC
    jmp DWORD PTR [_mixerGetLineInfoAPtr]
_ASM_mixerGetLineInfoA@8 ENDP

_ASM_mixerGetLineInfoW@8 PROC
    jmp DWORD PTR [_mixerGetLineInfoWPtr]
_ASM_mixerGetLineInfoW@8 ENDP

_ASM_mixerGetNumDevs@8 PROC
    jmp DWORD PTR [_mixerGetNumDevsPtr]
_ASM_mixerGetNumDevs@8 ENDP

_ASM_mixerMessage@8 PROC
    jmp DWORD PTR [_mixerMessagePtr]
_ASM_mixerMessage@8 ENDP

_ASM_mixerOpen@8 PROC
    jmp DWORD PTR [_mixerOpenPtr]
_ASM_mixerOpen@8 ENDP

_ASM_mixerSetControlDetails@8 PROC
    jmp DWORD PTR [_mixerSetControlDetailsPtr]
_ASM_mixerSetControlDetails@8 ENDP

_ASM_mmDrvInstall@8 PROC
    jmp DWORD PTR [_mmDrvInstallPtr]
_ASM_mmDrvInstall@8 ENDP

_ASM_mmGetCurrentTask@8 PROC
    jmp DWORD PTR [_mmGetCurrentTaskPtr]
_ASM_mmGetCurrentTask@8 ENDP

_ASM_mmTaskBlock@8 PROC
    jmp DWORD PTR [_mmTaskBlockPtr]
_ASM_mmTaskBlock@8 ENDP

_ASM_mmTaskCreate@8 PROC
    jmp DWORD PTR [_mmTaskCreatePtr]
_ASM_mmTaskCreate@8 ENDP

_ASM_mmTaskSignal@8 PROC
    jmp DWORD PTR [_mmTaskSignalPtr]
_ASM_mmTaskSignal@8 ENDP

_ASM_mmTaskYield@8 PROC
    jmp DWORD PTR [_mmTaskYieldPtr]
_ASM_mmTaskYield@8 ENDP

_ASM_mmioAdvance@8 PROC
    jmp DWORD PTR [_mmioAdvancePtr]
_ASM_mmioAdvance@8 ENDP

_ASM_mmioAscend@8 PROC
    jmp DWORD PTR [_mmioAscendPtr]
_ASM_mmioAscend@8 ENDP

_ASM_mmioClose@8 PROC
    jmp DWORD PTR [_mmioClosePtr]
_ASM_mmioClose@8 ENDP

_ASM_mmioCreateChunk@8 PROC
    jmp DWORD PTR [_mmioCreateChunkPtr]
_ASM_mmioCreateChunk@8 ENDP

_ASM_mmioDescend@8 PROC
    jmp DWORD PTR [_mmioDescendPtr]
_ASM_mmioDescend@8 ENDP

_ASM_mmioFlush@8 PROC
    jmp DWORD PTR [_mmioFlushPtr]
_ASM_mmioFlush@8 ENDP

_ASM_mmioGetInfo@8 PROC
    jmp DWORD PTR [_mmioGetInfoPtr]
_ASM_mmioGetInfo@8 ENDP

_ASM_mmioInstallIOProcA@8 PROC
    jmp DWORD PTR [_mmioInstallIOProcAPtr]
_ASM_mmioInstallIOProcA@8 ENDP

_ASM_mmioInstallIOProcW@8 PROC
    jmp DWORD PTR [_mmioInstallIOProcWPtr]
_ASM_mmioInstallIOProcW@8 ENDP

_ASM_mmioOpenA@8 PROC
    jmp DWORD PTR [_mmioOpenAPtr]
_ASM_mmioOpenA@8 ENDP

_ASM_mmioOpenW@8 PROC
    jmp DWORD PTR [_mmioOpenWPtr]
_ASM_mmioOpenW@8 ENDP

_ASM_mmioRead@8 PROC
    jmp DWORD PTR [_mmioReadPtr]
_ASM_mmioRead@8 ENDP

_ASM_mmioRenameA@8 PROC
    jmp DWORD PTR [_mmioRenameAPtr]
_ASM_mmioRenameA@8 ENDP

_ASM_mmioRenameW@8 PROC
    jmp DWORD PTR [_mmioRenameWPtr]
_ASM_mmioRenameW@8 ENDP

_ASM_mmioSeek@8 PROC
    jmp DWORD PTR [_mmioSeekPtr]
_ASM_mmioSeek@8 ENDP

_ASM_mmioSendMessage@8 PROC
    jmp DWORD PTR [_mmioSendMessagePtr]
_ASM_mmioSendMessage@8 ENDP

_ASM_mmioSetBuffer@8 PROC
    jmp DWORD PTR [_mmioSetBufferPtr]
_ASM_mmioSetBuffer@8 ENDP

_ASM_mmioSetInfo@8 PROC
    jmp DWORD PTR [_mmioSetInfoPtr]
_ASM_mmioSetInfo@8 ENDP

_ASM_mmioStringToFOURCCA@8 PROC
    jmp DWORD PTR [_mmioStringToFOURCCAPtr]
_ASM_mmioStringToFOURCCA@8 ENDP

_ASM_mmioStringToFOURCCW@8 PROC
    jmp DWORD PTR [_mmioStringToFOURCCWPtr]
_ASM_mmioStringToFOURCCW@8 ENDP

_ASM_mmioWrite@8 PROC
    jmp DWORD PTR [_mmioWritePtr]
_ASM_mmioWrite@8 ENDP

_ASM_mmsystemGetVersion@8 PROC
    jmp DWORD PTR [_mmsystemGetVersionPtr]
_ASM_mmsystemGetVersion@8 ENDP

_ASM_sndPlaySoundA@8 PROC
    jmp DWORD PTR [_sndPlaySoundAPtr]
_ASM_sndPlaySoundA@8 ENDP

_ASM_sndPlaySoundW@8 PROC
    jmp DWORD PTR [_sndPlaySoundWPtr]
_ASM_sndPlaySoundW@8 ENDP

_ASM_timeBeginPeriod@8 PROC
    jmp DWORD PTR [_timeBeginPeriodPtr]
_ASM_timeBeginPeriod@8 ENDP

_ASM_timeEndPeriod@8 PROC
    jmp DWORD PTR [_timeEndPeriodPtr]
_ASM_timeEndPeriod@8 ENDP

_ASM_timeGetDevCaps@8 PROC
    jmp DWORD PTR [_timeGetDevCapsPtr]
_ASM_timeGetDevCaps@8 ENDP

_ASM_timeGetSystemTime@8 PROC
    jmp DWORD PTR [_timeGetSystemTimePtr]
_ASM_timeGetSystemTime@8 ENDP

_ASM_timeGetTime@8 PROC
    jmp DWORD PTR [_timeGetTimePtr]
_ASM_timeGetTime@8 ENDP

_ASM_timeKillEvent@8 PROC
    jmp DWORD PTR [_timeKillEventPtr]
_ASM_timeKillEvent@8 ENDP

_ASM_timeSetEvent@8 PROC
    jmp DWORD PTR [_timeSetEventPtr]
_ASM_timeSetEvent@8 ENDP

_ASM_waveInAddBuffer@8 PROC
    jmp DWORD PTR [_waveInAddBufferPtr]
_ASM_waveInAddBuffer@8 ENDP

_ASM_waveInClose@8 PROC
    jmp DWORD PTR [_waveInClosePtr]
_ASM_waveInClose@8 ENDP

_ASM_waveInGetDevCapsA@8 PROC
    jmp DWORD PTR [_waveInGetDevCapsAPtr]
_ASM_waveInGetDevCapsA@8 ENDP

_ASM_waveInGetDevCapsW@8 PROC
    jmp DWORD PTR [_waveInGetDevCapsWPtr]
_ASM_waveInGetDevCapsW@8 ENDP

_ASM_waveInGetErrorTextA@8 PROC
    jmp DWORD PTR [_waveInGetErrorTextAPtr]
_ASM_waveInGetErrorTextA@8 ENDP

_ASM_waveInGetErrorTextW@8 PROC
    jmp DWORD PTR [_waveInGetErrorTextWPtr]
_ASM_waveInGetErrorTextW@8 ENDP

_ASM_waveInGetID@8 PROC
    jmp DWORD PTR [_waveInGetIDPtr]
_ASM_waveInGetID@8 ENDP

_ASM_waveInGetNumDevs@8 PROC
    jmp DWORD PTR [_waveInGetNumDevsPtr]
_ASM_waveInGetNumDevs@8 ENDP

_ASM_waveInGetPosition@8 PROC
    jmp DWORD PTR [_waveInGetPositionPtr]
_ASM_waveInGetPosition@8 ENDP

_ASM_waveInMessage@8 PROC
    jmp DWORD PTR [_waveInMessagePtr]
_ASM_waveInMessage@8 ENDP

_ASM_waveInOpen@8 PROC
    jmp DWORD PTR [_waveInOpenPtr]
_ASM_waveInOpen@8 ENDP

_ASM_waveInPrepareHeader@8 PROC
    jmp DWORD PTR [_waveInPrepareHeaderPtr]
_ASM_waveInPrepareHeader@8 ENDP

_ASM_waveInReset@8 PROC
    jmp DWORD PTR [_waveInResetPtr]
_ASM_waveInReset@8 ENDP

_ASM_waveInStart@8 PROC
    jmp DWORD PTR [_waveInStartPtr]
_ASM_waveInStart@8 ENDP

_ASM_waveInStop@8 PROC
    jmp DWORD PTR [_waveInStopPtr]
_ASM_waveInStop@8 ENDP

_ASM_waveInUnprepareHeader@8 PROC
    jmp DWORD PTR [_waveInUnprepareHeaderPtr]
_ASM_waveInUnprepareHeader@8 ENDP

_ASM_waveOutBreakLoop@8 PROC
    jmp DWORD PTR [_waveOutBreakLoopPtr]
_ASM_waveOutBreakLoop@8 ENDP

_ASM_waveOutClose@8 PROC
    jmp DWORD PTR [_waveOutClosePtr]
_ASM_waveOutClose@8 ENDP

_ASM_waveOutGetDevCapsA@8 PROC
    jmp DWORD PTR [_waveOutGetDevCapsAPtr]
_ASM_waveOutGetDevCapsA@8 ENDP

_ASM_waveOutGetDevCapsW@8 PROC
    jmp DWORD PTR [_waveOutGetDevCapsWPtr]
_ASM_waveOutGetDevCapsW@8 ENDP

_ASM_waveOutGetErrorTextA@8 PROC
    jmp DWORD PTR [_waveOutGetErrorTextAPtr]
_ASM_waveOutGetErrorTextA@8 ENDP

_ASM_waveOutGetErrorTextW@8 PROC
    jmp DWORD PTR [_waveOutGetErrorTextWPtr]
_ASM_waveOutGetErrorTextW@8 ENDP

_ASM_waveOutGetID@8 PROC
    jmp DWORD PTR [_waveOutGetIDPtr]
_ASM_waveOutGetID@8 ENDP

_ASM_waveOutGetNumDevs@8 PROC
    jmp DWORD PTR [_waveOutGetNumDevsPtr]
_ASM_waveOutGetNumDevs@8 ENDP

_ASM_waveOutGetPitch@8 PROC
    jmp DWORD PTR [_waveOutGetPitchPtr]
_ASM_waveOutGetPitch@8 ENDP

_ASM_waveOutGetPlaybackRate@8 PROC
    jmp DWORD PTR [_waveOutGetPlaybackRatePtr]
_ASM_waveOutGetPlaybackRate@8 ENDP

_ASM_waveOutGetPosition@8 PROC
    jmp DWORD PTR [_waveOutGetPositionPtr]
_ASM_waveOutGetPosition@8 ENDP

_ASM_waveOutGetVolume@8 PROC
    jmp DWORD PTR [_waveOutGetVolumePtr]
_ASM_waveOutGetVolume@8 ENDP

_ASM_waveOutMessage@8 PROC
    jmp DWORD PTR [_waveOutMessagePtr]
_ASM_waveOutMessage@8 ENDP

_ASM_waveOutOpen@8 PROC
    jmp DWORD PTR [_waveOutOpenPtr]
_ASM_waveOutOpen@8 ENDP

_ASM_waveOutPause@8 PROC
    jmp DWORD PTR [_waveOutPausePtr]
_ASM_waveOutPause@8 ENDP

_ASM_waveOutPrepareHeader@8 PROC
    jmp DWORD PTR [_waveOutPrepareHeaderPtr]
_ASM_waveOutPrepareHeader@8 ENDP

_ASM_waveOutReset@8 PROC
    jmp DWORD PTR [_waveOutResetPtr]
_ASM_waveOutReset@8 ENDP

_ASM_waveOutRestart@8 PROC
    jmp DWORD PTR [_waveOutRestartPtr]
_ASM_waveOutRestart@8 ENDP

_ASM_waveOutSetPitch@8 PROC
    jmp DWORD PTR [_waveOutSetPitchPtr]
_ASM_waveOutSetPitch@8 ENDP

_ASM_waveOutSetPlaybackRate@8 PROC
    jmp DWORD PTR [_waveOutSetPlaybackRatePtr]
_ASM_waveOutSetPlaybackRate@8 ENDP

_ASM_waveOutSetVolume@8 PROC
    jmp DWORD PTR [_waveOutSetVolumePtr]
_ASM_waveOutSetVolume@8 ENDP

_ASM_waveOutUnprepareHeader@8 PROC
    jmp DWORD PTR [_waveOutUnprepareHeaderPtr]
_ASM_waveOutUnprepareHeader@8 ENDP

_ASM_waveOutWrite@8 PROC
    jmp DWORD PTR [_waveOutWritePtr]
_ASM_waveOutWrite@8 ENDP


END

